/* plugin.c generated by valac 0.14.2, the Vala compiler
 * generated from plugin.vala, do not modify */

/*
 * Copyright (C) 2011 Simon Busch <morphis@gravedo.de>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 **/

#include <glib.h>
#include <glib-object.h>
#include <connman/network.h>
#include <connman/device.h>
#include <fsobasics.h>
#include <gio/gio.h>
#include <string.h>


#define FSO_GSM_TYPE_MODEM_HANDLER (fso_gsm_modem_handler_get_type ())
#define FSO_GSM_MODEM_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_MODEM_HANDLER, FsoGsmModemHandler))
#define FSO_GSM_MODEM_HANDLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_MODEM_HANDLER, FsoGsmModemHandlerClass))
#define FSO_GSM_IS_MODEM_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_MODEM_HANDLER))
#define FSO_GSM_IS_MODEM_HANDLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_MODEM_HANDLER))
#define FSO_GSM_MODEM_HANDLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_MODEM_HANDLER, FsoGsmModemHandlerClass))

typedef struct _FsoGsmModemHandler FsoGsmModemHandler;
typedef struct _FsoGsmModemHandlerClass FsoGsmModemHandlerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))


extern struct connman_network_driver network_driver;
struct connman_network_driver network_driver = {0};
extern struct connman_device_driver modem_driver;
struct connman_device_driver modem_driver = {0};
extern FsoGsmModemHandler* modem;
FsoGsmModemHandler* modem = NULL;

GType fso_gsm_modem_handler_get_type (void) G_GNUC_CONST;
gint network_probe (struct connman_network* network);
gint network_remove (struct connman_network* network);
gint network_connect (struct connman_network* network);
void fso_gsm_modem_handler_connect_network (FsoGsmModemHandler* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
gint fso_gsm_modem_handler_connect_network_finish (FsoGsmModemHandler* self, GAsyncResult* _res_);
gint network_disconnect (struct connman_network* network);
void fso_gsm_modem_handler_disconnect_network (FsoGsmModemHandler* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
gint fso_gsm_modem_handler_disconnect_network_finish (FsoGsmModemHandler* self, GAsyncResult* _res_);
gint modem_probe (struct connman_device* device);
gint modem_remove (struct connman_device* device);
gint modem_enable (struct connman_device* device);
gint modem_disable (struct connman_device* device);
gint fsogsm_plugin_init (void);
FsoGsmModemHandler* fso_gsm_modem_handler_new (void);
FsoGsmModemHandler* fso_gsm_modem_handler_construct (GType object_type);
void fso_gsm_modem_handler_initialize (FsoGsmModemHandler* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
void fso_gsm_modem_handler_initialize_finish (FsoGsmModemHandler* self, GAsyncResult* _res_);
static gint _network_probe_connman_network_driver_func (struct connman_network* network);
static gint _network_remove_connman_network_driver_func (struct connman_network* network);
static gint _network_connect_connman_network_driver_func (struct connman_network* network);
static gint _network_disconnect_connman_network_driver_func (struct connman_network* network);
static gint _modem_probe_connman_device_driver_func (struct connman_device* device);
static gint _modem_remove_connman_device_driver_func (struct connman_device* device);
static gint _modem_enable_connman_device_driver_func (struct connman_device* device);
static gint _modem_disable_connman_device_driver_func (struct connman_device* device);
void fsogsm_plugin_exit (void);
void fso_gsm_modem_handler_shutdown (FsoGsmModemHandler* self);


gint network_probe (struct connman_network* network) {
	gint result = 0;
	g_return_val_if_fail (network != NULL, 0);
	g_debug ("plugin.vala:28: network_probe()");
	result = 0;
	return result;
}


gint network_remove (struct connman_network* network) {
	gint result = 0;
	g_return_val_if_fail (network != NULL, 0);
	g_debug ("plugin.vala:34: network_remove()");
	result = 0;
	return result;
}


gint network_connect (struct connman_network* network) {
	gint result = 0;
	FsoGsmModemHandler* _tmp0_;
	g_return_val_if_fail (network != NULL, 0);
	_tmp0_ = modem;
	fso_gsm_modem_handler_connect_network (_tmp0_, NULL, NULL);
	result = 0;
	return result;
}


gint network_disconnect (struct connman_network* network) {
	gint result = 0;
	FsoGsmModemHandler* _tmp0_;
	g_return_val_if_fail (network != NULL, 0);
	_tmp0_ = modem;
	fso_gsm_modem_handler_disconnect_network (_tmp0_, NULL, NULL);
	result = 0;
	return result;
}


gint modem_probe (struct connman_device* device) {
	gint result = 0;
	g_return_val_if_fail (device != NULL, 0);
	g_debug ("plugin.vala:52: modem_probe()");
	result = 0;
	return result;
}


gint modem_remove (struct connman_device* device) {
	gint result = 0;
	g_return_val_if_fail (device != NULL, 0);
	g_debug ("plugin.vala:58: modem_remove()");
	result = 0;
	return result;
}


gint modem_enable (struct connman_device* device) {
	gint result = 0;
	g_return_val_if_fail (device != NULL, 0);
	result = 0;
	return result;
}


gint modem_disable (struct connman_device* device) {
	gint result = 0;
	g_return_val_if_fail (device != NULL, 0);
	result = 0;
	return result;
}


static gint _network_probe_connman_network_driver_func (struct connman_network* network) {
	gint result;
	result = network_probe (network);
	return result;
}


static gint _network_remove_connman_network_driver_func (struct connman_network* network) {
	gint result;
	result = network_remove (network);
	return result;
}


static gint _network_connect_connman_network_driver_func (struct connman_network* network) {
	gint result;
	result = network_connect (network);
	return result;
}


static gint _network_disconnect_connman_network_driver_func (struct connman_network* network) {
	gint result;
	result = network_disconnect (network);
	return result;
}


static gint _modem_probe_connman_device_driver_func (struct connman_device* device) {
	gint result;
	result = modem_probe (device);
	return result;
}


static gint _modem_remove_connman_device_driver_func (struct connman_device* device) {
	gint result;
	result = modem_remove (device);
	return result;
}


static gint _modem_enable_connman_device_driver_func (struct connman_device* device) {
	gint result;
	result = modem_enable (device);
	return result;
}


static gint _modem_disable_connman_device_driver_func (struct connman_device* device) {
	gint result;
	result = modem_disable (device);
	return result;
}


gint fsogsm_plugin_init (void) {
	gint result = 0;
	gint err = 0;
	FsoGsmModemHandler* _tmp0_;
	FsoGsmModemHandler* _tmp1_;
	gchar* _tmp2_;
	struct connman_network_driver _tmp3_ = {0};
	gchar* _tmp4_;
	struct connman_device_driver _tmp5_ = {0};
	gint _tmp6_ = 0;
	gint _tmp7_;
	gint _tmp8_ = 0;
	gint _tmp9_;
	_tmp0_ = fso_gsm_modem_handler_new ();
	_g_object_unref0 (modem);
	modem = _tmp0_;
	_tmp1_ = modem;
	fso_gsm_modem_handler_initialize (_tmp1_, NULL, NULL);
	_tmp2_ = g_strdup ("network");
	memset (&_tmp3_, 0, sizeof (struct connman_network_driver));
	_g_free0 (_tmp3_.name);
	_tmp3_.name = _tmp2_;
	_tmp3_.type = CONNMAN_NETWORK_TYPE_CELLULAR;
	_tmp3_.probe = _network_probe_connman_network_driver_func;
	_tmp3_.remove = _network_remove_connman_network_driver_func;
	_tmp3_.connect = _network_connect_connman_network_driver_func;
	_tmp3_.disconnect = _network_disconnect_connman_network_driver_func;
	 (&network_driver);
	network_driver = _tmp3_;
	_tmp4_ = g_strdup ("modem");
	memset (&_tmp5_, 0, sizeof (struct connman_device_driver));
	_g_free0 (_tmp5_.name);
	_tmp5_.name = _tmp4_;
	_tmp5_.type = CONNMAN_DEVICE_TYPE_CELLULAR;
	_tmp5_.probe = _modem_probe_connman_device_driver_func;
	_tmp5_.remove = _modem_remove_connman_device_driver_func;
	_tmp5_.enable = _modem_enable_connman_device_driver_func;
	_tmp5_.disable = _modem_disable_connman_device_driver_func;
	 (&modem_driver);
	modem_driver = _tmp5_;
	_tmp6_ = connman_network_driver_register (&network_driver);
	err = _tmp6_;
	_tmp7_ = err;
	if (_tmp7_ < 0) {
		result = err;
		return result;
	}
	_tmp8_ = connman_device_driver_register (&modem_driver);
	err = _tmp8_;
	_tmp9_ = err;
	if (_tmp9_ < 0) {
		connman_network_driver_register (&network_driver);
		result = err;
		return result;
	}
	result = 0;
	return result;
}


void fsogsm_plugin_exit (void) {
	FsoGsmModemHandler* _tmp0_;
	_tmp0_ = modem;
	fso_gsm_modem_handler_shutdown (_tmp0_);
	connman_network_driver_register (&network_driver);
}



