/* device_servicemanager.c generated by valac 0.16.0, the Vala compiler
 * generated from device_servicemanager.vala, do not modify */

/*
 * Copyright (C) 2009-2012 Michael 'Mickey' Lauer <mlauer@vanille-media.de>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <fsobasics.h>
#include <fsogsm.h>
#include <gio/gio.h>
#include <fsoframework.h>
#include <stdlib.h>
#include <string.h>
#include <freesmartphone.h>


#define FSO_GSM_TYPE_SERVICE_MANAGER (fso_gsm_service_manager_get_type ())
#define FSO_GSM_SERVICE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_SERVICE_MANAGER, FsoGsmServiceManager))
#define FSO_GSM_SERVICE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_SERVICE_MANAGER, FsoGsmServiceManagerClass))
#define FSO_GSM_IS_SERVICE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_SERVICE_MANAGER))
#define FSO_GSM_IS_SERVICE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_SERVICE_MANAGER))
#define FSO_GSM_SERVICE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_SERVICE_MANAGER, FsoGsmServiceManagerClass))

typedef struct _FsoGsmServiceManager FsoGsmServiceManager;
typedef struct _FsoGsmServiceManagerClass FsoGsmServiceManagerClass;
typedef struct _FsoGsmServiceManagerPrivate FsoGsmServiceManagerPrivate;

#define FSO_GSM_TYPE_DEVICE_SERVICE_MANAGER (fso_gsm_device_service_manager_get_type ())
#define FSO_GSM_DEVICE_SERVICE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_DEVICE_SERVICE_MANAGER, FsoGsmDeviceServiceManager))
#define FSO_GSM_DEVICE_SERVICE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_DEVICE_SERVICE_MANAGER, FsoGsmDeviceServiceManagerClass))
#define FSO_GSM_IS_DEVICE_SERVICE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_DEVICE_SERVICE_MANAGER))
#define FSO_GSM_IS_DEVICE_SERVICE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_DEVICE_SERVICE_MANAGER))
#define FSO_GSM_DEVICE_SERVICE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_DEVICE_SERVICE_MANAGER, FsoGsmDeviceServiceManagerClass))

typedef struct _FsoGsmDeviceServiceManager FsoGsmDeviceServiceManager;
typedef struct _FsoGsmDeviceServiceManagerClass FsoGsmDeviceServiceManagerClass;
typedef struct _FsoGsmDeviceServiceManagerPrivate FsoGsmDeviceServiceManagerPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _fso_gsm_device_service_manager_onModemHangupAsyncData fso_gsm_device_service_manager_onModemHangupAsyncData;

#define FSO_GSM_TYPE_SERVICE (fso_gsm_service_get_type ())
#define FSO_GSM_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_SERVICE, FsoGsmService))
#define FSO_GSM_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_SERVICE, FsoGsmServiceClass))
#define FSO_GSM_IS_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_SERVICE))
#define FSO_GSM_IS_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_SERVICE))
#define FSO_GSM_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_SERVICE, FsoGsmServiceClass))

typedef struct _FsoGsmService FsoGsmService;
typedef struct _FsoGsmServiceClass FsoGsmServiceClass;

#define FSO_GSM_TYPE_INFO_SERVICE (fso_gsm_info_service_get_type ())
#define FSO_GSM_INFO_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_INFO_SERVICE, FsoGsmInfoService))
#define FSO_GSM_INFO_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_INFO_SERVICE, FsoGsmInfoServiceClass))
#define FSO_GSM_IS_INFO_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_INFO_SERVICE))
#define FSO_GSM_IS_INFO_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_INFO_SERVICE))
#define FSO_GSM_INFO_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_INFO_SERVICE, FsoGsmInfoServiceClass))

typedef struct _FsoGsmInfoService FsoGsmInfoService;
typedef struct _FsoGsmInfoServiceClass FsoGsmInfoServiceClass;

#define FSO_GSM_TYPE_DEVICE_RTC_SERVICE (fso_gsm_device_rtc_service_get_type ())
#define FSO_GSM_DEVICE_RTC_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_DEVICE_RTC_SERVICE, FsoGsmDeviceRtcService))
#define FSO_GSM_DEVICE_RTC_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_DEVICE_RTC_SERVICE, FsoGsmDeviceRtcServiceClass))
#define FSO_GSM_IS_DEVICE_RTC_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_DEVICE_RTC_SERVICE))
#define FSO_GSM_IS_DEVICE_RTC_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_DEVICE_RTC_SERVICE))
#define FSO_GSM_DEVICE_RTC_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_DEVICE_RTC_SERVICE, FsoGsmDeviceRtcServiceClass))

typedef struct _FsoGsmDeviceRtcService FsoGsmDeviceRtcService;
typedef struct _FsoGsmDeviceRtcServiceClass FsoGsmDeviceRtcServiceClass;

#define FSO_GSM_TYPE_DEVICE_POWER_SUPPLY_SERVICE (fso_gsm_device_power_supply_service_get_type ())
#define FSO_GSM_DEVICE_POWER_SUPPLY_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_DEVICE_POWER_SUPPLY_SERVICE, FsoGsmDevicePowerSupplyService))
#define FSO_GSM_DEVICE_POWER_SUPPLY_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_DEVICE_POWER_SUPPLY_SERVICE, FsoGsmDevicePowerSupplyServiceClass))
#define FSO_GSM_IS_DEVICE_POWER_SUPPLY_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_DEVICE_POWER_SUPPLY_SERVICE))
#define FSO_GSM_IS_DEVICE_POWER_SUPPLY_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_DEVICE_POWER_SUPPLY_SERVICE))
#define FSO_GSM_DEVICE_POWER_SUPPLY_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_DEVICE_POWER_SUPPLY_SERVICE, FsoGsmDevicePowerSupplyServiceClass))

typedef struct _FsoGsmDevicePowerSupplyService FsoGsmDevicePowerSupplyService;
typedef struct _FsoGsmDevicePowerSupplyServiceClass FsoGsmDevicePowerSupplyServiceClass;

#define FSO_GSM_TYPE_GSM_DEVICE_SERVICE (fso_gsm_gsm_device_service_get_type ())
#define FSO_GSM_GSM_DEVICE_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_GSM_DEVICE_SERVICE, FsoGsmGsmDeviceService))
#define FSO_GSM_GSM_DEVICE_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_GSM_DEVICE_SERVICE, FsoGsmGsmDeviceServiceClass))
#define FSO_GSM_IS_GSM_DEVICE_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_GSM_DEVICE_SERVICE))
#define FSO_GSM_IS_GSM_DEVICE_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_GSM_DEVICE_SERVICE))
#define FSO_GSM_GSM_DEVICE_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_GSM_DEVICE_SERVICE, FsoGsmGsmDeviceServiceClass))

typedef struct _FsoGsmGsmDeviceService FsoGsmGsmDeviceService;
typedef struct _FsoGsmGsmDeviceServiceClass FsoGsmGsmDeviceServiceClass;

#define FSO_GSM_TYPE_GSM_DEBUG_SERVICE (fso_gsm_gsm_debug_service_get_type ())
#define FSO_GSM_GSM_DEBUG_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_GSM_DEBUG_SERVICE, FsoGsmGsmDebugService))
#define FSO_GSM_GSM_DEBUG_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_GSM_DEBUG_SERVICE, FsoGsmGsmDebugServiceClass))
#define FSO_GSM_IS_GSM_DEBUG_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_GSM_DEBUG_SERVICE))
#define FSO_GSM_IS_GSM_DEBUG_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_GSM_DEBUG_SERVICE))
#define FSO_GSM_GSM_DEBUG_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_GSM_DEBUG_SERVICE, FsoGsmGsmDebugServiceClass))

typedef struct _FsoGsmGsmDebugService FsoGsmGsmDebugService;
typedef struct _FsoGsmGsmDebugServiceClass FsoGsmGsmDebugServiceClass;

#define FSO_GSM_TYPE_GSM_CALL_SERVICE (fso_gsm_gsm_call_service_get_type ())
#define FSO_GSM_GSM_CALL_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_GSM_CALL_SERVICE, FsoGsmGsmCallService))
#define FSO_GSM_GSM_CALL_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_GSM_CALL_SERVICE, FsoGsmGsmCallServiceClass))
#define FSO_GSM_IS_GSM_CALL_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_GSM_CALL_SERVICE))
#define FSO_GSM_IS_GSM_CALL_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_GSM_CALL_SERVICE))
#define FSO_GSM_GSM_CALL_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_GSM_CALL_SERVICE, FsoGsmGsmCallServiceClass))

typedef struct _FsoGsmGsmCallService FsoGsmGsmCallService;
typedef struct _FsoGsmGsmCallServiceClass FsoGsmGsmCallServiceClass;

#define FSO_GSM_TYPE_GSM_CALL_FORWARDING_SERVICE (fso_gsm_gsm_call_forwarding_service_get_type ())
#define FSO_GSM_GSM_CALL_FORWARDING_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_GSM_CALL_FORWARDING_SERVICE, FsoGsmGsmCallForwardingService))
#define FSO_GSM_GSM_CALL_FORWARDING_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_GSM_CALL_FORWARDING_SERVICE, FsoGsmGsmCallForwardingServiceClass))
#define FSO_GSM_IS_GSM_CALL_FORWARDING_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_GSM_CALL_FORWARDING_SERVICE))
#define FSO_GSM_IS_GSM_CALL_FORWARDING_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_GSM_CALL_FORWARDING_SERVICE))
#define FSO_GSM_GSM_CALL_FORWARDING_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_GSM_CALL_FORWARDING_SERVICE, FsoGsmGsmCallForwardingServiceClass))

typedef struct _FsoGsmGsmCallForwardingService FsoGsmGsmCallForwardingService;
typedef struct _FsoGsmGsmCallForwardingServiceClass FsoGsmGsmCallForwardingServiceClass;

#define FSO_GSM_TYPE_GSM_CB_SERVICE (fso_gsm_gsm_cb_service_get_type ())
#define FSO_GSM_GSM_CB_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_GSM_CB_SERVICE, FsoGsmGsmCbService))
#define FSO_GSM_GSM_CB_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_GSM_CB_SERVICE, FsoGsmGsmCbServiceClass))
#define FSO_GSM_IS_GSM_CB_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_GSM_CB_SERVICE))
#define FSO_GSM_IS_GSM_CB_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_GSM_CB_SERVICE))
#define FSO_GSM_GSM_CB_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_GSM_CB_SERVICE, FsoGsmGsmCbServiceClass))

typedef struct _FsoGsmGsmCbService FsoGsmGsmCbService;
typedef struct _FsoGsmGsmCbServiceClass FsoGsmGsmCbServiceClass;

#define FSO_GSM_TYPE_GSM_HZ_SERVICE (fso_gsm_gsm_hz_service_get_type ())
#define FSO_GSM_GSM_HZ_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_GSM_HZ_SERVICE, FsoGsmGsmHzService))
#define FSO_GSM_GSM_HZ_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_GSM_HZ_SERVICE, FsoGsmGsmHzServiceClass))
#define FSO_GSM_IS_GSM_HZ_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_GSM_HZ_SERVICE))
#define FSO_GSM_IS_GSM_HZ_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_GSM_HZ_SERVICE))
#define FSO_GSM_GSM_HZ_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_GSM_HZ_SERVICE, FsoGsmGsmHzServiceClass))

typedef struct _FsoGsmGsmHzService FsoGsmGsmHzService;
typedef struct _FsoGsmGsmHzServiceClass FsoGsmGsmHzServiceClass;

#define FSO_GSM_TYPE_GSM_MONITOR_SERVICE (fso_gsm_gsm_monitor_service_get_type ())
#define FSO_GSM_GSM_MONITOR_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_GSM_MONITOR_SERVICE, FsoGsmGsmMonitorService))
#define FSO_GSM_GSM_MONITOR_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_GSM_MONITOR_SERVICE, FsoGsmGsmMonitorServiceClass))
#define FSO_GSM_IS_GSM_MONITOR_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_GSM_MONITOR_SERVICE))
#define FSO_GSM_IS_GSM_MONITOR_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_GSM_MONITOR_SERVICE))
#define FSO_GSM_GSM_MONITOR_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_GSM_MONITOR_SERVICE, FsoGsmGsmMonitorServiceClass))

typedef struct _FsoGsmGsmMonitorService FsoGsmGsmMonitorService;
typedef struct _FsoGsmGsmMonitorServiceClass FsoGsmGsmMonitorServiceClass;

#define FSO_GSM_TYPE_GSM_NETWORK_SERVICE (fso_gsm_gsm_network_service_get_type ())
#define FSO_GSM_GSM_NETWORK_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_GSM_NETWORK_SERVICE, FsoGsmGsmNetworkService))
#define FSO_GSM_GSM_NETWORK_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_GSM_NETWORK_SERVICE, FsoGsmGsmNetworkServiceClass))
#define FSO_GSM_IS_GSM_NETWORK_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_GSM_NETWORK_SERVICE))
#define FSO_GSM_IS_GSM_NETWORK_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_GSM_NETWORK_SERVICE))
#define FSO_GSM_GSM_NETWORK_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_GSM_NETWORK_SERVICE, FsoGsmGsmNetworkServiceClass))

typedef struct _FsoGsmGsmNetworkService FsoGsmGsmNetworkService;
typedef struct _FsoGsmGsmNetworkServiceClass FsoGsmGsmNetworkServiceClass;

#define FSO_GSM_TYPE_GSM_PDP_SERVICE (fso_gsm_gsm_pdp_service_get_type ())
#define FSO_GSM_GSM_PDP_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_GSM_PDP_SERVICE, FsoGsmGsmPdpService))
#define FSO_GSM_GSM_PDP_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_GSM_PDP_SERVICE, FsoGsmGsmPdpServiceClass))
#define FSO_GSM_IS_GSM_PDP_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_GSM_PDP_SERVICE))
#define FSO_GSM_IS_GSM_PDP_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_GSM_PDP_SERVICE))
#define FSO_GSM_GSM_PDP_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_GSM_PDP_SERVICE, FsoGsmGsmPdpServiceClass))

typedef struct _FsoGsmGsmPdpService FsoGsmGsmPdpService;
typedef struct _FsoGsmGsmPdpServiceClass FsoGsmGsmPdpServiceClass;

#define FSO_GSM_TYPE_GSM_SIM_SERVICE (fso_gsm_gsm_sim_service_get_type ())
#define FSO_GSM_GSM_SIM_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_GSM_SIM_SERVICE, FsoGsmGsmSimService))
#define FSO_GSM_GSM_SIM_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_GSM_SIM_SERVICE, FsoGsmGsmSimServiceClass))
#define FSO_GSM_IS_GSM_SIM_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_GSM_SIM_SERVICE))
#define FSO_GSM_IS_GSM_SIM_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_GSM_SIM_SERVICE))
#define FSO_GSM_GSM_SIM_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_GSM_SIM_SERVICE, FsoGsmGsmSimServiceClass))

typedef struct _FsoGsmGsmSimService FsoGsmGsmSimService;
typedef struct _FsoGsmGsmSimServiceClass FsoGsmGsmSimServiceClass;

#define FSO_GSM_TYPE_GSM_SMS_SERVICE (fso_gsm_gsm_sms_service_get_type ())
#define FSO_GSM_GSM_SMS_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_GSM_SMS_SERVICE, FsoGsmGsmSmsService))
#define FSO_GSM_GSM_SMS_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_GSM_SMS_SERVICE, FsoGsmGsmSmsServiceClass))
#define FSO_GSM_IS_GSM_SMS_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_GSM_SMS_SERVICE))
#define FSO_GSM_IS_GSM_SMS_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_GSM_SMS_SERVICE))
#define FSO_GSM_GSM_SMS_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_GSM_SMS_SERVICE, FsoGsmGsmSmsServiceClass))

typedef struct _FsoGsmGsmSmsService FsoGsmGsmSmsService;
typedef struct _FsoGsmGsmSmsServiceClass FsoGsmGsmSmsServiceClass;

#define FSO_GSM_TYPE_GSM_VOICE_MAIL_SERVICE (fso_gsm_gsm_voice_mail_service_get_type ())
#define FSO_GSM_GSM_VOICE_MAIL_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_GSM_VOICE_MAIL_SERVICE, FsoGsmGsmVoiceMailService))
#define FSO_GSM_GSM_VOICE_MAIL_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_GSM_VOICE_MAIL_SERVICE, FsoGsmGsmVoiceMailServiceClass))
#define FSO_GSM_IS_GSM_VOICE_MAIL_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_GSM_VOICE_MAIL_SERVICE))
#define FSO_GSM_IS_GSM_VOICE_MAIL_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_GSM_VOICE_MAIL_SERVICE))
#define FSO_GSM_GSM_VOICE_MAIL_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_GSM_VOICE_MAIL_SERVICE, FsoGsmGsmVoiceMailServiceClass))

typedef struct _FsoGsmGsmVoiceMailService FsoGsmGsmVoiceMailService;
typedef struct _FsoGsmGsmVoiceMailServiceClass FsoGsmGsmVoiceMailServiceClass;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _FsoGsmDeviceServiceManagerEnableData FsoGsmDeviceServiceManagerEnableData;
typedef struct _FsoGsmDeviceServiceManagerDisableData FsoGsmDeviceServiceManagerDisableData;
typedef struct _FsoGsmDeviceServiceManagerSuspendData FsoGsmDeviceServiceManagerSuspendData;
typedef struct _FsoGsmDeviceServiceManagerResumeData FsoGsmDeviceServiceManagerResumeData;

struct _FsoGsmServiceManager {
	FsoFrameworkAbstractObject parent_instance;
	FsoGsmServiceManagerPrivate * priv;
};

struct _FsoGsmServiceManagerClass {
	FsoFrameworkAbstractObjectClass parent_class;
	void (*enable) (FsoGsmServiceManager* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	gboolean (*enable_finish) (FsoGsmServiceManager* self, GAsyncResult* _res_);
	void (*disable) (FsoGsmServiceManager* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*disable_finish) (FsoGsmServiceManager* self, GAsyncResult* _res_);
	void (*suspend) (FsoGsmServiceManager* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*suspend_finish) (FsoGsmServiceManager* self, GAsyncResult* _res_);
	void (*resume) (FsoGsmServiceManager* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*resume_finish) (FsoGsmServiceManager* self, GAsyncResult* _res_);
};

struct _FsoGsmDeviceServiceManager {
	FsoGsmServiceManager parent_instance;
	FsoGsmDeviceServiceManagerPrivate * priv;
};

struct _FsoGsmDeviceServiceManagerClass {
	FsoGsmServiceManagerClass parent_class;
};

struct _FsoGsmDeviceServiceManagerPrivate {
	FsoGsmModem* modem;
	gboolean _initialized;
};

struct _fso_gsm_device_service_manager_onModemHangupAsyncData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	FsoGsmDeviceServiceManager* self;
	gboolean _tmp0_;
	gboolean ok;
	gboolean _tmp1_;
};

struct _FsoGsmDeviceServiceManagerEnableData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	FsoGsmDeviceServiceManager* self;
	gboolean result;
	FsoGsmModem* _tmp0_;
	gboolean _tmp1_;
	gboolean ok;
	gboolean _tmp2_;
	FsoFrameworkLogger* _tmp3_;
	FsoFrameworkLogger* _tmp4_;
};

struct _FsoGsmDeviceServiceManagerDisableData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	FsoGsmDeviceServiceManager* self;
	FsoGsmModem* _tmp0_;
	FsoFrameworkLogger* _tmp1_;
};

struct _FsoGsmDeviceServiceManagerSuspendData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	FsoGsmDeviceServiceManager* self;
	FsoGsmModem* _tmp0_;
	gboolean _tmp1_;
	gboolean ok;
	gboolean _tmp2_;
	FsoFrameworkLogger* _tmp3_;
	FsoFrameworkLogger* _tmp4_;
};

struct _FsoGsmDeviceServiceManagerResumeData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	FsoGsmDeviceServiceManager* self;
	FsoGsmModem* _tmp0_;
	gboolean _tmp1_;
	gboolean ok;
	gboolean _tmp2_;
	FsoFrameworkLogger* _tmp3_;
	FsoFrameworkLogger* _tmp4_;
};


static gpointer fso_gsm_device_service_manager_parent_class = NULL;
static GType fso_gsm_device_service_manager_type_id = 0;

GType fso_gsm_service_manager_get_type (void) G_GNUC_CONST;
GType fso_gsm_service_manager_register_type (GTypeModule * module);
GType fso_gsm_device_service_manager_get_type (void) G_GNUC_CONST;
GType fso_gsm_device_service_manager_register_type (GTypeModule * module);
#define FSO_GSM_DEVICE_SERVICE_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), FSO_GSM_TYPE_DEVICE_SERVICE_MANAGER, FsoGsmDeviceServiceManagerPrivate))
enum  {
	FSO_GSM_DEVICE_SERVICE_MANAGER_DUMMY_PROPERTY,
	FSO_GSM_DEVICE_SERVICE_MANAGER_INITIALIZED
};
static void fso_gsm_device_service_manager_onModemHangup (FsoGsmDeviceServiceManager* self);
static gboolean __lambda2_ (FsoGsmDeviceServiceManager* self);
static void fso_gsm_device_service_manager_onModemHangupAsync (FsoGsmDeviceServiceManager* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void fso_gsm_device_service_manager_onModemHangupAsync_finish (FsoGsmDeviceServiceManager* self, GAsyncResult* _res_);
static gboolean ___lambda2__gsource_func (gpointer self);
static void fso_gsm_device_service_manager_onModemHangupAsync_data_free (gpointer _data);
static gboolean fso_gsm_device_service_manager_onModemHangupAsync_co (fso_gsm_device_service_manager_onModemHangupAsyncData* _data_);
void fso_gsm_service_manager_enable (FsoGsmServiceManager* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
gboolean fso_gsm_service_manager_enable_finish (FsoGsmServiceManager* self, GAsyncResult* _res_);
static void fso_gsm_device_service_manager_onModemHangupAsync_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
FsoGsmDeviceServiceManager* fso_gsm_device_service_manager_new (FsoGsmModem* modem, FsoFrameworkSubsystem* subsystem);
FsoGsmDeviceServiceManager* fso_gsm_device_service_manager_construct (GType object_type, FsoGsmModem* modem, FsoFrameworkSubsystem* subsystem);
FsoGsmServiceManager* fso_gsm_service_manager_construct (GType object_type, FsoFrameworkSubsystem* subsystem, const gchar* serviceName, const gchar* servicePath);
GType fso_gsm_service_get_type (void) G_GNUC_CONST;
GType fso_gsm_service_register_type (GTypeModule * module);
void fso_gsm_service_manager_registerService (FsoGsmServiceManager* self, GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, FsoGsmService* serviceObject);
FsoGsmInfoService* fso_gsm_info_service_new (void);
FsoGsmInfoService* fso_gsm_info_service_construct (GType object_type);
GType fso_gsm_info_service_get_type (void) G_GNUC_CONST;
GType fso_gsm_info_service_register_type (GTypeModule * module);
FsoGsmDeviceRtcService* fso_gsm_device_rtc_service_new (void);
FsoGsmDeviceRtcService* fso_gsm_device_rtc_service_construct (GType object_type);
GType fso_gsm_device_rtc_service_get_type (void) G_GNUC_CONST;
GType fso_gsm_device_rtc_service_register_type (GTypeModule * module);
FsoGsmDevicePowerSupplyService* fso_gsm_device_power_supply_service_new (void);
FsoGsmDevicePowerSupplyService* fso_gsm_device_power_supply_service_construct (GType object_type);
GType fso_gsm_device_power_supply_service_get_type (void) G_GNUC_CONST;
GType fso_gsm_device_power_supply_service_register_type (GTypeModule * module);
FsoGsmGsmDeviceService* fso_gsm_gsm_device_service_new (void);
FsoGsmGsmDeviceService* fso_gsm_gsm_device_service_construct (GType object_type);
GType fso_gsm_gsm_device_service_get_type (void) G_GNUC_CONST;
GType fso_gsm_gsm_device_service_register_type (GTypeModule * module);
FsoGsmGsmDebugService* fso_gsm_gsm_debug_service_new (void);
FsoGsmGsmDebugService* fso_gsm_gsm_debug_service_construct (GType object_type);
GType fso_gsm_gsm_debug_service_get_type (void) G_GNUC_CONST;
GType fso_gsm_gsm_debug_service_register_type (GTypeModule * module);
FsoGsmGsmCallService* fso_gsm_gsm_call_service_new (void);
FsoGsmGsmCallService* fso_gsm_gsm_call_service_construct (GType object_type);
GType fso_gsm_gsm_call_service_get_type (void) G_GNUC_CONST;
GType fso_gsm_gsm_call_service_register_type (GTypeModule * module);
FsoGsmGsmCallForwardingService* fso_gsm_gsm_call_forwarding_service_new (void);
FsoGsmGsmCallForwardingService* fso_gsm_gsm_call_forwarding_service_construct (GType object_type);
GType fso_gsm_gsm_call_forwarding_service_get_type (void) G_GNUC_CONST;
GType fso_gsm_gsm_call_forwarding_service_register_type (GTypeModule * module);
FsoGsmGsmCbService* fso_gsm_gsm_cb_service_new (void);
FsoGsmGsmCbService* fso_gsm_gsm_cb_service_construct (GType object_type);
GType fso_gsm_gsm_cb_service_get_type (void) G_GNUC_CONST;
GType fso_gsm_gsm_cb_service_register_type (GTypeModule * module);
FsoGsmGsmHzService* fso_gsm_gsm_hz_service_new (void);
FsoGsmGsmHzService* fso_gsm_gsm_hz_service_construct (GType object_type);
GType fso_gsm_gsm_hz_service_get_type (void) G_GNUC_CONST;
GType fso_gsm_gsm_hz_service_register_type (GTypeModule * module);
FsoGsmGsmMonitorService* fso_gsm_gsm_monitor_service_new (void);
FsoGsmGsmMonitorService* fso_gsm_gsm_monitor_service_construct (GType object_type);
GType fso_gsm_gsm_monitor_service_get_type (void) G_GNUC_CONST;
GType fso_gsm_gsm_monitor_service_register_type (GTypeModule * module);
FsoGsmGsmNetworkService* fso_gsm_gsm_network_service_new (void);
FsoGsmGsmNetworkService* fso_gsm_gsm_network_service_construct (GType object_type);
GType fso_gsm_gsm_network_service_get_type (void) G_GNUC_CONST;
GType fso_gsm_gsm_network_service_register_type (GTypeModule * module);
FsoGsmGsmPdpService* fso_gsm_gsm_pdp_service_new (void);
FsoGsmGsmPdpService* fso_gsm_gsm_pdp_service_construct (GType object_type);
GType fso_gsm_gsm_pdp_service_get_type (void) G_GNUC_CONST;
GType fso_gsm_gsm_pdp_service_register_type (GTypeModule * module);
FsoGsmGsmSimService* fso_gsm_gsm_sim_service_new (void);
FsoGsmGsmSimService* fso_gsm_gsm_sim_service_construct (GType object_type);
GType fso_gsm_gsm_sim_service_get_type (void) G_GNUC_CONST;
GType fso_gsm_gsm_sim_service_register_type (GTypeModule * module);
FsoGsmGsmSmsService* fso_gsm_gsm_sms_service_new (void);
FsoGsmGsmSmsService* fso_gsm_gsm_sms_service_construct (GType object_type);
GType fso_gsm_gsm_sms_service_get_type (void) G_GNUC_CONST;
GType fso_gsm_gsm_sms_service_register_type (GTypeModule * module);
FsoGsmGsmVoiceMailService* fso_gsm_gsm_voice_mail_service_new (void);
FsoGsmGsmVoiceMailService* fso_gsm_gsm_voice_mail_service_construct (GType object_type);
GType fso_gsm_gsm_voice_mail_service_get_type (void) G_GNUC_CONST;
GType fso_gsm_gsm_voice_mail_service_register_type (GTypeModule * module);
static void _fso_gsm_device_service_manager_onModemHangup_fso_gsm_modem_hangup (FsoGsmModem* _sender, gpointer self);
void fso_gsm_service_manager_assignModem (FsoGsmServiceManager* self, FsoGsmModem* modem);
static void fso_gsm_device_service_manager_set_initialized (FsoGsmDeviceServiceManager* self, gboolean value);
static void fso_gsm_device_service_manager_real_enable_data_free (gpointer _data);
static void fso_gsm_device_service_manager_real_enable (FsoGsmServiceManager* base, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean fso_gsm_device_service_manager_real_enable_co (FsoGsmDeviceServiceManagerEnableData* _data_);
static void fso_gsm_device_service_manager_enable_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void fso_gsm_device_service_manager_real_disable_data_free (gpointer _data);
static void fso_gsm_device_service_manager_real_disable (FsoGsmServiceManager* base, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean fso_gsm_device_service_manager_real_disable_co (FsoGsmDeviceServiceManagerDisableData* _data_);
static void fso_gsm_device_service_manager_disable_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void fso_gsm_device_service_manager_real_suspend_data_free (gpointer _data);
static void fso_gsm_device_service_manager_real_suspend (FsoGsmServiceManager* base, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean fso_gsm_device_service_manager_real_suspend_co (FsoGsmDeviceServiceManagerSuspendData* _data_);
static void fso_gsm_device_service_manager_suspend_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void fso_gsm_device_service_manager_real_resume_data_free (gpointer _data);
static void fso_gsm_device_service_manager_real_resume (FsoGsmServiceManager* base, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean fso_gsm_device_service_manager_real_resume_co (FsoGsmDeviceServiceManagerResumeData* _data_);
static void fso_gsm_device_service_manager_resume_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
gboolean fso_gsm_device_service_manager_get_initialized (FsoGsmDeviceServiceManager* self);
static void fso_gsm_device_service_manager_finalize (GObject* obj);
static void _vala_fso_gsm_device_service_manager_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_fso_gsm_device_service_manager_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gboolean __lambda2_ (FsoGsmDeviceServiceManager* self) {
	gboolean result = FALSE;
	fso_gsm_device_service_manager_onModemHangupAsync (self, NULL, NULL);
	result = FALSE;
	return result;
}


static gboolean ___lambda2__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda2_ (self);
	return result;
}


static void fso_gsm_device_service_manager_onModemHangup (FsoGsmDeviceServiceManager* self) {
	FsoFrameworkLogger* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = ((FsoFrameworkAbstractObject*) self)->logger;
	fso_framework_logger_warning (_tmp0_, "Modem no longer responding; trying to reopen in 5 seconds");
	g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) 5, ___lambda2__gsource_func, g_object_ref (self), g_object_unref);
}


static void fso_gsm_device_service_manager_onModemHangupAsync_data_free (gpointer _data) {
	fso_gsm_device_service_manager_onModemHangupAsyncData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (fso_gsm_device_service_manager_onModemHangupAsyncData, _data_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void fso_gsm_device_service_manager_onModemHangupAsync (FsoGsmDeviceServiceManager* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	fso_gsm_device_service_manager_onModemHangupAsyncData* _data_;
	FsoGsmDeviceServiceManager* _tmp0_;
	_data_ = g_slice_new0 (fso_gsm_device_service_manager_onModemHangupAsyncData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, fso_gsm_device_service_manager_onModemHangupAsync);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, fso_gsm_device_service_manager_onModemHangupAsync_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	fso_gsm_device_service_manager_onModemHangupAsync_co (_data_);
}


static void fso_gsm_device_service_manager_onModemHangupAsync_finish (FsoGsmDeviceServiceManager* self, GAsyncResult* _res_) {
	fso_gsm_device_service_manager_onModemHangupAsyncData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void fso_gsm_device_service_manager_onModemHangupAsync_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	fso_gsm_device_service_manager_onModemHangupAsyncData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	fso_gsm_device_service_manager_onModemHangupAsync_co (_data_);
}


static gboolean fso_gsm_device_service_manager_onModemHangupAsync_co (fso_gsm_device_service_manager_onModemHangupAsyncData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_state_ = 1;
	fso_gsm_service_manager_enable ((FsoGsmServiceManager*) _data_->self, fso_gsm_device_service_manager_onModemHangupAsync_ready, _data_);
	return FALSE;
	_state_1:
	_data_->_tmp0_ = FALSE;
	_data_->_tmp0_ = fso_gsm_service_manager_enable_finish ((FsoGsmServiceManager*) _data_->self, _data_->_res_);
	_data_->ok = _data_->_tmp0_;
	_data_->_tmp1_ = _data_->ok;
	if (!_data_->_tmp1_) {
		fso_gsm_device_service_manager_onModemHangup (_data_->self);
	}
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void _fso_gsm_device_service_manager_onModemHangup_fso_gsm_modem_hangup (FsoGsmModem* _sender, gpointer self) {
	fso_gsm_device_service_manager_onModemHangup (self);
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


FsoGsmDeviceServiceManager* fso_gsm_device_service_manager_construct (GType object_type, FsoGsmModem* modem, FsoFrameworkSubsystem* subsystem) {
	FsoGsmDeviceServiceManager * self = NULL;
	FsoFrameworkSubsystem* _tmp0_;
	FsoGsmInfoService* _tmp1_;
	FsoGsmInfoService* _tmp2_;
	FsoGsmDeviceRtcService* _tmp3_;
	FsoGsmDeviceRtcService* _tmp4_;
	FsoGsmDevicePowerSupplyService* _tmp5_;
	FsoGsmDevicePowerSupplyService* _tmp6_;
	FsoGsmGsmDeviceService* _tmp7_;
	FsoGsmGsmDeviceService* _tmp8_;
	FsoGsmGsmDebugService* _tmp9_;
	FsoGsmGsmDebugService* _tmp10_;
	FsoGsmGsmCallService* _tmp11_;
	FsoGsmGsmCallService* _tmp12_;
	FsoGsmGsmCallForwardingService* _tmp13_;
	FsoGsmGsmCallForwardingService* _tmp14_;
	FsoGsmGsmCbService* _tmp15_;
	FsoGsmGsmCbService* _tmp16_;
	FsoGsmGsmHzService* _tmp17_;
	FsoGsmGsmHzService* _tmp18_;
	FsoGsmGsmMonitorService* _tmp19_;
	FsoGsmGsmMonitorService* _tmp20_;
	FsoGsmGsmNetworkService* _tmp21_;
	FsoGsmGsmNetworkService* _tmp22_;
	FsoGsmGsmPdpService* _tmp23_;
	FsoGsmGsmPdpService* _tmp24_;
	FsoGsmGsmSimService* _tmp25_;
	FsoGsmGsmSimService* _tmp26_;
	FsoGsmGsmSmsService* _tmp27_;
	FsoGsmGsmSmsService* _tmp28_;
	FsoGsmGsmVoiceMailService* _tmp29_;
	FsoGsmGsmVoiceMailService* _tmp30_;
	FsoGsmModem* _tmp31_;
	FsoGsmModem* _tmp32_;
	FsoGsmModem* _tmp33_;
	FsoGsmModem* _tmp34_;
	FsoGsmModem* _tmp35_;
	FsoFrameworkSmartKeyFile* _tmp36_;
	gchar* _tmp37_ = NULL;
	gchar* modemtype;
	FsoFrameworkLogger* _tmp38_;
	const gchar* _tmp39_ = NULL;
	gchar* _tmp40_ = NULL;
	gchar* _tmp41_;
	g_return_val_if_fail (modem != NULL, NULL);
	g_return_val_if_fail (subsystem != NULL, NULL);
	_tmp0_ = subsystem;
	self = (FsoGsmDeviceServiceManager*) fso_gsm_service_manager_construct (object_type, _tmp0_, FSO_FRAMEWORK_GSM_ServiceDBusName, FSO_FRAMEWORK_GSM_DeviceServicePath);
	_tmp1_ = fso_gsm_info_service_new ();
	_tmp2_ = _tmp1_;
	fso_gsm_service_manager_registerService (FSO_GSM_SERVICE_MANAGER (self), FREE_SMARTPHONE_TYPE_INFO, (GBoxedCopyFunc) g_object_ref, g_object_unref, (FsoGsmService*) _tmp2_);
	_g_object_unref0 (_tmp2_);
	_tmp3_ = fso_gsm_device_rtc_service_new ();
	_tmp4_ = _tmp3_;
	fso_gsm_service_manager_registerService (FSO_GSM_SERVICE_MANAGER (self), FREE_SMARTPHONE_DEVICE_TYPE_REALTIME_CLOCK, (GBoxedCopyFunc) g_object_ref, g_object_unref, (FsoGsmService*) _tmp4_);
	_g_object_unref0 (_tmp4_);
	_tmp5_ = fso_gsm_device_power_supply_service_new ();
	_tmp6_ = _tmp5_;
	fso_gsm_service_manager_registerService (FSO_GSM_SERVICE_MANAGER (self), FREE_SMARTPHONE_DEVICE_TYPE_POWER_SUPPLY, (GBoxedCopyFunc) g_object_ref, g_object_unref, (FsoGsmService*) _tmp6_);
	_g_object_unref0 (_tmp6_);
	_tmp7_ = fso_gsm_gsm_device_service_new ();
	_tmp8_ = _tmp7_;
	fso_gsm_service_manager_registerService (FSO_GSM_SERVICE_MANAGER (self), FREE_SMARTPHONE_GSM_TYPE_DEVICE, (GBoxedCopyFunc) g_object_ref, g_object_unref, (FsoGsmService*) _tmp8_);
	_g_object_unref0 (_tmp8_);
	_tmp9_ = fso_gsm_gsm_debug_service_new ();
	_tmp10_ = _tmp9_;
	fso_gsm_service_manager_registerService (FSO_GSM_SERVICE_MANAGER (self), FREE_SMARTPHONE_GSM_TYPE_DEBUG, (GBoxedCopyFunc) g_object_ref, g_object_unref, (FsoGsmService*) _tmp10_);
	_g_object_unref0 (_tmp10_);
	_tmp11_ = fso_gsm_gsm_call_service_new ();
	_tmp12_ = _tmp11_;
	fso_gsm_service_manager_registerService (FSO_GSM_SERVICE_MANAGER (self), FREE_SMARTPHONE_GSM_TYPE_CALL, (GBoxedCopyFunc) g_object_ref, g_object_unref, (FsoGsmService*) _tmp12_);
	_g_object_unref0 (_tmp12_);
	_tmp13_ = fso_gsm_gsm_call_forwarding_service_new ();
	_tmp14_ = _tmp13_;
	fso_gsm_service_manager_registerService (FSO_GSM_SERVICE_MANAGER (self), FREE_SMARTPHONE_GSM_TYPE_CALL_FORWARDING, (GBoxedCopyFunc) g_object_ref, g_object_unref, (FsoGsmService*) _tmp14_);
	_g_object_unref0 (_tmp14_);
	_tmp15_ = fso_gsm_gsm_cb_service_new ();
	_tmp16_ = _tmp15_;
	fso_gsm_service_manager_registerService (FSO_GSM_SERVICE_MANAGER (self), FREE_SMARTPHONE_GSM_TYPE_CB, (GBoxedCopyFunc) g_object_ref, g_object_unref, (FsoGsmService*) _tmp16_);
	_g_object_unref0 (_tmp16_);
	_tmp17_ = fso_gsm_gsm_hz_service_new ();
	_tmp18_ = _tmp17_;
	fso_gsm_service_manager_registerService (FSO_GSM_SERVICE_MANAGER (self), FREE_SMARTPHONE_GSM_TYPE_HZ, (GBoxedCopyFunc) g_object_ref, g_object_unref, (FsoGsmService*) _tmp18_);
	_g_object_unref0 (_tmp18_);
	_tmp19_ = fso_gsm_gsm_monitor_service_new ();
	_tmp20_ = _tmp19_;
	fso_gsm_service_manager_registerService (FSO_GSM_SERVICE_MANAGER (self), FREE_SMARTPHONE_GSM_TYPE_MONITOR, (GBoxedCopyFunc) g_object_ref, g_object_unref, (FsoGsmService*) _tmp20_);
	_g_object_unref0 (_tmp20_);
	_tmp21_ = fso_gsm_gsm_network_service_new ();
	_tmp22_ = _tmp21_;
	fso_gsm_service_manager_registerService (FSO_GSM_SERVICE_MANAGER (self), FREE_SMARTPHONE_GSM_TYPE_NETWORK, (GBoxedCopyFunc) g_object_ref, g_object_unref, (FsoGsmService*) _tmp22_);
	_g_object_unref0 (_tmp22_);
	_tmp23_ = fso_gsm_gsm_pdp_service_new ();
	_tmp24_ = _tmp23_;
	fso_gsm_service_manager_registerService (FSO_GSM_SERVICE_MANAGER (self), FREE_SMARTPHONE_GSM_TYPE_PDP, (GBoxedCopyFunc) g_object_ref, g_object_unref, (FsoGsmService*) _tmp24_);
	_g_object_unref0 (_tmp24_);
	_tmp25_ = fso_gsm_gsm_sim_service_new ();
	_tmp26_ = _tmp25_;
	fso_gsm_service_manager_registerService (FSO_GSM_SERVICE_MANAGER (self), FREE_SMARTPHONE_GSM_TYPE_SIM, (GBoxedCopyFunc) g_object_ref, g_object_unref, (FsoGsmService*) _tmp26_);
	_g_object_unref0 (_tmp26_);
	_tmp27_ = fso_gsm_gsm_sms_service_new ();
	_tmp28_ = _tmp27_;
	fso_gsm_service_manager_registerService (FSO_GSM_SERVICE_MANAGER (self), FREE_SMARTPHONE_GSM_TYPE_SMS, (GBoxedCopyFunc) g_object_ref, g_object_unref, (FsoGsmService*) _tmp28_);
	_g_object_unref0 (_tmp28_);
	_tmp29_ = fso_gsm_gsm_voice_mail_service_new ();
	_tmp30_ = _tmp29_;
	fso_gsm_service_manager_registerService (FSO_GSM_SERVICE_MANAGER (self), FREE_SMARTPHONE_GSM_TYPE_VOICE_MAIL, (GBoxedCopyFunc) g_object_ref, g_object_unref, (FsoGsmService*) _tmp30_);
	_g_object_unref0 (_tmp30_);
	_tmp31_ = modem;
	_tmp32_ = _g_object_ref0 (_tmp31_);
	_g_object_unref0 (self->priv->modem);
	self->priv->modem = _tmp32_;
	_tmp33_ = modem;
	fso_gsm_modem_set_parent (_tmp33_, (FsoGsmIServiceProvider*) self);
	_tmp34_ = modem;
	g_signal_connect_object (_tmp34_, "hangup", (GCallback) _fso_gsm_device_service_manager_onModemHangup_fso_gsm_modem_hangup, self, 0);
	_tmp35_ = modem;
	fso_gsm_service_manager_assignModem ((FsoGsmServiceManager*) self, _tmp35_);
	fso_gsm_device_service_manager_set_initialized (self, TRUE);
	_tmp36_ = fso_framework_theConfig;
	_tmp37_ = fso_framework_smart_key_file_stringValue (_tmp36_, "fsogsm", "modem_type", "none");
	modemtype = _tmp37_;
	_tmp38_ = ((FsoFrameworkAbstractObject*) self)->logger;
	_tmp39_ = string_to_string (modemtype);
	_tmp40_ = g_strconcat ("Ready. Configured for modem ", _tmp39_, NULL);
	_tmp41_ = _tmp40_;
	fso_framework_logger_info (_tmp38_, _tmp41_);
	_g_free0 (_tmp41_);
	_g_free0 (modemtype);
	return self;
}


FsoGsmDeviceServiceManager* fso_gsm_device_service_manager_new (FsoGsmModem* modem, FsoFrameworkSubsystem* subsystem) {
	return fso_gsm_device_service_manager_construct (FSO_GSM_TYPE_DEVICE_SERVICE_MANAGER, modem, subsystem);
}


static void fso_gsm_device_service_manager_real_enable_data_free (gpointer _data) {
	FsoGsmDeviceServiceManagerEnableData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (FsoGsmDeviceServiceManagerEnableData, _data_);
}


static void fso_gsm_device_service_manager_real_enable (FsoGsmServiceManager* base, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	FsoGsmDeviceServiceManager * self;
	FsoGsmDeviceServiceManagerEnableData* _data_;
	FsoGsmDeviceServiceManager* _tmp0_;
	self = (FsoGsmDeviceServiceManager*) base;
	_data_ = g_slice_new0 (FsoGsmDeviceServiceManagerEnableData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, fso_gsm_device_service_manager_real_enable);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, fso_gsm_device_service_manager_real_enable_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	fso_gsm_device_service_manager_real_enable_co (_data_);
}


static gboolean fso_gsm_device_service_manager_real_enable_finish (FsoGsmServiceManager* base, GAsyncResult* _res_) {
	gboolean result;
	FsoGsmDeviceServiceManagerEnableData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
	result = _data_->result;
	return result;
}


static void fso_gsm_device_service_manager_enable_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	FsoGsmDeviceServiceManagerEnableData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	fso_gsm_device_service_manager_real_enable_co (_data_);
}


static gboolean fso_gsm_device_service_manager_real_enable_co (FsoGsmDeviceServiceManagerEnableData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = _data_->self->priv->modem;
	_data_->_state_ = 1;
	fso_gsm_modem_open (_data_->_tmp0_, fso_gsm_device_service_manager_enable_ready, _data_);
	return FALSE;
	_state_1:
	_data_->_tmp1_ = FALSE;
	_data_->_tmp1_ = fso_gsm_modem_open_finish (_data_->_tmp0_, _data_->_res_);
	_data_->ok = _data_->_tmp1_;
	_data_->_tmp2_ = _data_->ok;
	if (!_data_->_tmp2_) {
		_data_->_tmp3_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
		fso_framework_logger_error (_data_->_tmp3_, "Can't open modem");
		_data_->result = FALSE;
		if (_data_->_state_ == 0) {
			g_simple_async_result_complete_in_idle (_data_->_async_result);
		} else {
			g_simple_async_result_complete (_data_->_async_result);
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	} else {
		_data_->_tmp4_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
		fso_framework_logger_info (_data_->_tmp4_, "Modem opened successfully");
		_data_->result = TRUE;
		if (_data_->_state_ == 0) {
			g_simple_async_result_complete_in_idle (_data_->_async_result);
		} else {
			g_simple_async_result_complete (_data_->_async_result);
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void fso_gsm_device_service_manager_real_disable_data_free (gpointer _data) {
	FsoGsmDeviceServiceManagerDisableData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (FsoGsmDeviceServiceManagerDisableData, _data_);
}


static void fso_gsm_device_service_manager_real_disable (FsoGsmServiceManager* base, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	FsoGsmDeviceServiceManager * self;
	FsoGsmDeviceServiceManagerDisableData* _data_;
	FsoGsmDeviceServiceManager* _tmp0_;
	self = (FsoGsmDeviceServiceManager*) base;
	_data_ = g_slice_new0 (FsoGsmDeviceServiceManagerDisableData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, fso_gsm_device_service_manager_real_disable);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, fso_gsm_device_service_manager_real_disable_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	fso_gsm_device_service_manager_real_disable_co (_data_);
}


static void fso_gsm_device_service_manager_real_disable_finish (FsoGsmServiceManager* base, GAsyncResult* _res_) {
	FsoGsmDeviceServiceManagerDisableData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void fso_gsm_device_service_manager_disable_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	FsoGsmDeviceServiceManagerDisableData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	fso_gsm_device_service_manager_real_disable_co (_data_);
}


static gboolean fso_gsm_device_service_manager_real_disable_co (FsoGsmDeviceServiceManagerDisableData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = _data_->self->priv->modem;
	_data_->_state_ = 1;
	fso_gsm_modem_close (_data_->_tmp0_, fso_gsm_device_service_manager_disable_ready, _data_);
	return FALSE;
	_state_1:
	fso_gsm_modem_close_finish (_data_->_tmp0_, _data_->_res_);
	_data_->_tmp1_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
	fso_framework_logger_info (_data_->_tmp1_, "Modem closed successfully");
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void fso_gsm_device_service_manager_real_suspend_data_free (gpointer _data) {
	FsoGsmDeviceServiceManagerSuspendData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (FsoGsmDeviceServiceManagerSuspendData, _data_);
}


static void fso_gsm_device_service_manager_real_suspend (FsoGsmServiceManager* base, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	FsoGsmDeviceServiceManager * self;
	FsoGsmDeviceServiceManagerSuspendData* _data_;
	FsoGsmDeviceServiceManager* _tmp0_;
	self = (FsoGsmDeviceServiceManager*) base;
	_data_ = g_slice_new0 (FsoGsmDeviceServiceManagerSuspendData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, fso_gsm_device_service_manager_real_suspend);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, fso_gsm_device_service_manager_real_suspend_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	fso_gsm_device_service_manager_real_suspend_co (_data_);
}


static void fso_gsm_device_service_manager_real_suspend_finish (FsoGsmServiceManager* base, GAsyncResult* _res_) {
	FsoGsmDeviceServiceManagerSuspendData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void fso_gsm_device_service_manager_suspend_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	FsoGsmDeviceServiceManagerSuspendData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	fso_gsm_device_service_manager_real_suspend_co (_data_);
}


static gboolean fso_gsm_device_service_manager_real_suspend_co (FsoGsmDeviceServiceManagerSuspendData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = _data_->self->priv->modem;
	_data_->_state_ = 1;
	fso_gsm_modem_suspend (_data_->_tmp0_, fso_gsm_device_service_manager_suspend_ready, _data_);
	return FALSE;
	_state_1:
	_data_->_tmp1_ = FALSE;
	_data_->_tmp1_ = fso_gsm_modem_suspend_finish (_data_->_tmp0_, _data_->_res_);
	_data_->ok = _data_->_tmp1_;
	_data_->_tmp2_ = _data_->ok;
	if (_data_->_tmp2_) {
		_data_->_tmp3_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
		fso_framework_logger_info (_data_->_tmp3_, "Modem suspended successfully");
	} else {
		_data_->_tmp4_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
		fso_framework_logger_warning (_data_->_tmp4_, "Modem not suspended; prepare yourself for spurious wakeups");
	}
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void fso_gsm_device_service_manager_real_resume_data_free (gpointer _data) {
	FsoGsmDeviceServiceManagerResumeData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (FsoGsmDeviceServiceManagerResumeData, _data_);
}


static void fso_gsm_device_service_manager_real_resume (FsoGsmServiceManager* base, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	FsoGsmDeviceServiceManager * self;
	FsoGsmDeviceServiceManagerResumeData* _data_;
	FsoGsmDeviceServiceManager* _tmp0_;
	self = (FsoGsmDeviceServiceManager*) base;
	_data_ = g_slice_new0 (FsoGsmDeviceServiceManagerResumeData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, fso_gsm_device_service_manager_real_resume);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, fso_gsm_device_service_manager_real_resume_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	fso_gsm_device_service_manager_real_resume_co (_data_);
}


static void fso_gsm_device_service_manager_real_resume_finish (FsoGsmServiceManager* base, GAsyncResult* _res_) {
	FsoGsmDeviceServiceManagerResumeData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void fso_gsm_device_service_manager_resume_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	FsoGsmDeviceServiceManagerResumeData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	fso_gsm_device_service_manager_real_resume_co (_data_);
}


static gboolean fso_gsm_device_service_manager_real_resume_co (FsoGsmDeviceServiceManagerResumeData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = _data_->self->priv->modem;
	_data_->_state_ = 1;
	fso_gsm_modem_resume (_data_->_tmp0_, fso_gsm_device_service_manager_resume_ready, _data_);
	return FALSE;
	_state_1:
	_data_->_tmp1_ = FALSE;
	_data_->_tmp1_ = fso_gsm_modem_resume_finish (_data_->_tmp0_, _data_->_res_);
	_data_->ok = _data_->_tmp1_;
	_data_->_tmp2_ = _data_->ok;
	if (_data_->_tmp2_) {
		_data_->_tmp3_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
		fso_framework_logger_info (_data_->_tmp3_, "Modem resumed successfully");
	} else {
		_data_->_tmp4_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
		fso_framework_logger_warning (_data_->_tmp4_, "Modem did not resume correctly");
	}
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


gboolean fso_gsm_device_service_manager_get_initialized (FsoGsmDeviceServiceManager* self) {
	gboolean result;
	gboolean _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_initialized;
	result = _tmp0_;
	return result;
}


static void fso_gsm_device_service_manager_set_initialized (FsoGsmDeviceServiceManager* self, gboolean value) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_initialized = _tmp0_;
	g_object_notify ((GObject *) self, "initialized");
}


static void fso_gsm_device_service_manager_class_init (FsoGsmDeviceServiceManagerClass * klass) {
	fso_gsm_device_service_manager_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (FsoGsmDeviceServiceManagerPrivate));
	FSO_GSM_SERVICE_MANAGER_CLASS (klass)->enable = fso_gsm_device_service_manager_real_enable;
	FSO_GSM_SERVICE_MANAGER_CLASS (klass)->enable_finish = fso_gsm_device_service_manager_real_enable_finish;
	FSO_GSM_SERVICE_MANAGER_CLASS (klass)->disable = fso_gsm_device_service_manager_real_disable;
	FSO_GSM_SERVICE_MANAGER_CLASS (klass)->disable_finish = fso_gsm_device_service_manager_real_disable_finish;
	FSO_GSM_SERVICE_MANAGER_CLASS (klass)->suspend = fso_gsm_device_service_manager_real_suspend;
	FSO_GSM_SERVICE_MANAGER_CLASS (klass)->suspend_finish = fso_gsm_device_service_manager_real_suspend_finish;
	FSO_GSM_SERVICE_MANAGER_CLASS (klass)->resume = fso_gsm_device_service_manager_real_resume;
	FSO_GSM_SERVICE_MANAGER_CLASS (klass)->resume_finish = fso_gsm_device_service_manager_real_resume_finish;
	G_OBJECT_CLASS (klass)->get_property = _vala_fso_gsm_device_service_manager_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_fso_gsm_device_service_manager_set_property;
	G_OBJECT_CLASS (klass)->finalize = fso_gsm_device_service_manager_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), FSO_GSM_DEVICE_SERVICE_MANAGER_INITIALIZED, g_param_spec_boolean ("initialized", "initialized", "initialized", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void fso_gsm_device_service_manager_instance_init (FsoGsmDeviceServiceManager * self) {
	self->priv = FSO_GSM_DEVICE_SERVICE_MANAGER_GET_PRIVATE (self);
	self->priv->_initialized = FALSE;
}


static void fso_gsm_device_service_manager_finalize (GObject* obj) {
	FsoGsmDeviceServiceManager * self;
	self = FSO_GSM_DEVICE_SERVICE_MANAGER (obj);
	_g_object_unref0 (self->priv->modem);
	G_OBJECT_CLASS (fso_gsm_device_service_manager_parent_class)->finalize (obj);
}


GType fso_gsm_device_service_manager_get_type (void) {
	return fso_gsm_device_service_manager_type_id;
}


GType fso_gsm_device_service_manager_register_type (GTypeModule * module) {
	static const GTypeInfo g_define_type_info = { sizeof (FsoGsmDeviceServiceManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) fso_gsm_device_service_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FsoGsmDeviceServiceManager), 0, (GInstanceInitFunc) fso_gsm_device_service_manager_instance_init, NULL };
	fso_gsm_device_service_manager_type_id = g_type_module_register_type (module, FSO_GSM_TYPE_SERVICE_MANAGER, "FsoGsmDeviceServiceManager", &g_define_type_info, 0);
	return fso_gsm_device_service_manager_type_id;
}


static void _vala_fso_gsm_device_service_manager_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	FsoGsmDeviceServiceManager * self;
	self = FSO_GSM_DEVICE_SERVICE_MANAGER (object);
	switch (property_id) {
		case FSO_GSM_DEVICE_SERVICE_MANAGER_INITIALIZED:
		g_value_set_boolean (value, fso_gsm_device_service_manager_get_initialized (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_fso_gsm_device_service_manager_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	FsoGsmDeviceServiceManager * self;
	self = FSO_GSM_DEVICE_SERVICE_MANAGER (object);
	switch (property_id) {
		case FSO_GSM_DEVICE_SERVICE_MANAGER_INITIALIZED:
		fso_gsm_device_service_manager_set_initialized (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



