/* atsms.c generated by valac 0.14.2, the Vala compiler
 * generated from atsms.vala, do not modify */

/*
 * Copyright (C) 2009-2011 Michael 'Mickey' Lauer <mlauer@vanille-media.de>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <fsobasics.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <smsutil.h>
#include <conversions.h>
#include <freesmartphone.h>
#include <fsotransport.h>
#include <util.h>


#define FSO_GSM_TYPE_SMS_HANDLER (fso_gsm_sms_handler_get_type ())
#define FSO_GSM_SMS_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_SMS_HANDLER, FsoGsmSmsHandler))
#define FSO_GSM_IS_SMS_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_SMS_HANDLER))
#define FSO_GSM_SMS_HANDLER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FSO_GSM_TYPE_SMS_HANDLER, FsoGsmSmsHandlerIface))

typedef struct _FsoGsmSmsHandler FsoGsmSmsHandler;
typedef struct _FsoGsmSmsHandlerIface FsoGsmSmsHandlerIface;

#define TYPE_WRAP_HEX_PDU (wrap_hex_pdu_get_type ())
#define WRAP_HEX_PDU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_WRAP_HEX_PDU, WrapHexPdu))
#define WRAP_HEX_PDU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_WRAP_HEX_PDU, WrapHexPduClass))
#define IS_WRAP_HEX_PDU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_WRAP_HEX_PDU))
#define IS_WRAP_HEX_PDU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_WRAP_HEX_PDU))
#define WRAP_HEX_PDU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_WRAP_HEX_PDU, WrapHexPduClass))

typedef struct _WrapHexPdu WrapHexPdu;
typedef struct _WrapHexPduClass WrapHexPduClass;

#define FSO_GSM_TYPE_ISMS_STORAGE (fso_gsm_isms_storage_get_type ())
#define FSO_GSM_ISMS_STORAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_ISMS_STORAGE, FsoGsmISmsStorage))
#define FSO_GSM_IS_ISMS_STORAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_ISMS_STORAGE))
#define FSO_GSM_ISMS_STORAGE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FSO_GSM_TYPE_ISMS_STORAGE, FsoGsmISmsStorageIface))

typedef struct _FsoGsmISmsStorage FsoGsmISmsStorage;
typedef struct _FsoGsmISmsStorageIface FsoGsmISmsStorageIface;

#define FSO_GSM_TYPE_ABSTRACT_SMS_HANDLER (fso_gsm_abstract_sms_handler_get_type ())
#define FSO_GSM_ABSTRACT_SMS_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_ABSTRACT_SMS_HANDLER, FsoGsmAbstractSmsHandler))
#define FSO_GSM_ABSTRACT_SMS_HANDLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_ABSTRACT_SMS_HANDLER, FsoGsmAbstractSmsHandlerClass))
#define FSO_GSM_IS_ABSTRACT_SMS_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_ABSTRACT_SMS_HANDLER))
#define FSO_GSM_IS_ABSTRACT_SMS_HANDLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_ABSTRACT_SMS_HANDLER))
#define FSO_GSM_ABSTRACT_SMS_HANDLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_ABSTRACT_SMS_HANDLER, FsoGsmAbstractSmsHandlerClass))

typedef struct _FsoGsmAbstractSmsHandler FsoGsmAbstractSmsHandler;
typedef struct _FsoGsmAbstractSmsHandlerClass FsoGsmAbstractSmsHandlerClass;
typedef struct _FsoGsmAbstractSmsHandlerPrivate FsoGsmAbstractSmsHandlerPrivate;

#define FSO_GSM_TYPE_AT_SMS_HANDLER (fso_gsm_at_sms_handler_get_type ())
#define FSO_GSM_AT_SMS_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_AT_SMS_HANDLER, FsoGsmAtSmsHandler))
#define FSO_GSM_AT_SMS_HANDLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_AT_SMS_HANDLER, FsoGsmAtSmsHandlerClass))
#define FSO_GSM_IS_AT_SMS_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_AT_SMS_HANDLER))
#define FSO_GSM_IS_AT_SMS_HANDLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_AT_SMS_HANDLER))
#define FSO_GSM_AT_SMS_HANDLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_AT_SMS_HANDLER, FsoGsmAtSmsHandlerClass))

typedef struct _FsoGsmAtSmsHandler FsoGsmAtSmsHandler;
typedef struct _FsoGsmAtSmsHandlerClass FsoGsmAtSmsHandlerClass;
typedef struct _FsoGsmAtSmsHandlerPrivate FsoGsmAtSmsHandlerPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define FSO_GSM_TYPE_MODEM (fso_gsm_modem_get_type ())
#define FSO_GSM_MODEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_MODEM, FsoGsmModem))
#define FSO_GSM_IS_MODEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_MODEM))
#define FSO_GSM_MODEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FSO_GSM_TYPE_MODEM, FsoGsmModemIface))

typedef struct _FsoGsmModem FsoGsmModem;
typedef struct _FsoGsmModemIface FsoGsmModemIface;

#define FSO_GSM_TYPE_CHANNEL (fso_gsm_channel_get_type ())
#define FSO_GSM_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_CHANNEL, FsoGsmChannel))
#define FSO_GSM_IS_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_CHANNEL))
#define FSO_GSM_CHANNEL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FSO_GSM_TYPE_CHANNEL, FsoGsmChannelIface))

typedef struct _FsoGsmChannel FsoGsmChannel;
typedef struct _FsoGsmChannelIface FsoGsmChannelIface;

#define FSO_GSM_MODEM_TYPE_STATUS (fso_gsm_modem_status_get_type ())

#define FSO_GSM_MODEM_TYPE_NETWORK_STATUS (fso_gsm_modem_network_status_get_type ())

#define FSO_GSM_TYPE_AT_COMMAND_SEQUENCE (fso_gsm_at_command_sequence_get_type ())
#define FSO_GSM_AT_COMMAND_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_AT_COMMAND_SEQUENCE, FsoGsmAtCommandSequence))
#define FSO_GSM_AT_COMMAND_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_AT_COMMAND_SEQUENCE, FsoGsmAtCommandSequenceClass))
#define FSO_GSM_IS_AT_COMMAND_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_AT_COMMAND_SEQUENCE))
#define FSO_GSM_IS_AT_COMMAND_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_AT_COMMAND_SEQUENCE))
#define FSO_GSM_AT_COMMAND_SEQUENCE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_AT_COMMAND_SEQUENCE, FsoGsmAtCommandSequenceClass))

typedef struct _FsoGsmAtCommandSequence FsoGsmAtCommandSequence;
typedef struct _FsoGsmAtCommandSequenceClass FsoGsmAtCommandSequenceClass;

#define FSO_GSM_TYPE_AT_COMMAND_QUEUE_COMMAND (fso_gsm_at_command_queue_command_get_type ())
#define FSO_GSM_AT_COMMAND_QUEUE_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_AT_COMMAND_QUEUE_COMMAND, FsoGsmAtCommandQueueCommand))
#define FSO_GSM_IS_AT_COMMAND_QUEUE_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_AT_COMMAND_QUEUE_COMMAND))
#define FSO_GSM_AT_COMMAND_QUEUE_COMMAND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FSO_GSM_TYPE_AT_COMMAND_QUEUE_COMMAND, FsoGsmAtCommandQueueCommandIface))

typedef struct _FsoGsmAtCommandQueueCommand FsoGsmAtCommandQueueCommand;
typedef struct _FsoGsmAtCommandQueueCommandIface FsoGsmAtCommandQueueCommandIface;

#define FSO_GSM_TYPE_AT_COMMAND (fso_gsm_at_command_get_type ())
#define FSO_GSM_AT_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_AT_COMMAND, FsoGsmAtCommand))
#define FSO_GSM_IS_AT_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_AT_COMMAND))
#define FSO_GSM_AT_COMMAND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FSO_GSM_TYPE_AT_COMMAND, FsoGsmAtCommandIface))

typedef struct _FsoGsmAtCommand FsoGsmAtCommand;
typedef struct _FsoGsmAtCommandIface FsoGsmAtCommandIface;

#define FSO_GSM_CONSTANTS_TYPE_AT_RESPONSE (fso_gsm_constants_at_response_get_type ())

#define FSO_GSM_MODEM_TYPE_DATA (fso_gsm_modem_data_get_type ())
#define FSO_GSM_MODEM_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_MODEM_TYPE_DATA, FsoGsmModemData))
#define FSO_GSM_MODEM_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_MODEM_TYPE_DATA, FsoGsmModemDataClass))
#define FSO_GSM_MODEM_IS_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_MODEM_TYPE_DATA))
#define FSO_GSM_MODEM_IS_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_MODEM_TYPE_DATA))
#define FSO_GSM_MODEM_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_MODEM_TYPE_DATA, FsoGsmModemDataClass))

typedef struct _FsoGsmModemData FsoGsmModemData;
typedef struct _FsoGsmModemDataClass FsoGsmModemDataClass;

#define FSO_GSM_TYPE_CALL_HANDLER (fso_gsm_call_handler_get_type ())
#define FSO_GSM_CALL_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_CALL_HANDLER, FsoGsmCallHandler))
#define FSO_GSM_IS_CALL_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_CALL_HANDLER))
#define FSO_GSM_CALL_HANDLER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FSO_GSM_TYPE_CALL_HANDLER, FsoGsmCallHandlerIface))

typedef struct _FsoGsmCallHandler FsoGsmCallHandler;
typedef struct _FsoGsmCallHandlerIface FsoGsmCallHandlerIface;

#define FSO_GSM_TYPE_CALL_INFO (fso_gsm_call_info_get_type ())
#define FSO_GSM_CALL_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_CALL_INFO, FsoGsmCallInfo))
#define FSO_GSM_CALL_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_CALL_INFO, FsoGsmCallInfoClass))
#define FSO_GSM_IS_CALL_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_CALL_INFO))
#define FSO_GSM_IS_CALL_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_CALL_INFO))
#define FSO_GSM_CALL_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_CALL_INFO, FsoGsmCallInfoClass))

typedef struct _FsoGsmCallInfo FsoGsmCallInfo;
typedef struct _FsoGsmCallInfoClass FsoGsmCallInfoClass;

#define FSO_GSM_TYPE_PHONEBOOK_HANDLER (fso_gsm_phonebook_handler_get_type ())
#define FSO_GSM_PHONEBOOK_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_PHONEBOOK_HANDLER, FsoGsmPhonebookHandler))
#define FSO_GSM_IS_PHONEBOOK_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_PHONEBOOK_HANDLER))
#define FSO_GSM_PHONEBOOK_HANDLER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FSO_GSM_TYPE_PHONEBOOK_HANDLER, FsoGsmPhonebookHandlerIface))

typedef struct _FsoGsmPhonebookHandler FsoGsmPhonebookHandler;
typedef struct _FsoGsmPhonebookHandlerIface FsoGsmPhonebookHandlerIface;

#define FSO_GSM_TYPE_PHONEBOOK_STORAGE (fso_gsm_phonebook_storage_get_type ())
#define FSO_GSM_PHONEBOOK_STORAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_PHONEBOOK_STORAGE, FsoGsmPhonebookStorage))
#define FSO_GSM_PHONEBOOK_STORAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_PHONEBOOK_STORAGE, FsoGsmPhonebookStorageClass))
#define FSO_GSM_IS_PHONEBOOK_STORAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_PHONEBOOK_STORAGE))
#define FSO_GSM_IS_PHONEBOOK_STORAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_PHONEBOOK_STORAGE))
#define FSO_GSM_PHONEBOOK_STORAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_PHONEBOOK_STORAGE, FsoGsmPhonebookStorageClass))

typedef struct _FsoGsmPhonebookStorage FsoGsmPhonebookStorage;
typedef struct _FsoGsmPhonebookStorageClass FsoGsmPhonebookStorageClass;

#define FSO_GSM_TYPE_WATCH_DOG (fso_gsm_watch_dog_get_type ())
#define FSO_GSM_WATCH_DOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_WATCH_DOG, FsoGsmWatchDog))
#define FSO_GSM_IS_WATCH_DOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_WATCH_DOG))
#define FSO_GSM_WATCH_DOG_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FSO_GSM_TYPE_WATCH_DOG, FsoGsmWatchDogIface))

typedef struct _FsoGsmWatchDog FsoGsmWatchDog;
typedef struct _FsoGsmWatchDogIface FsoGsmWatchDogIface;

#define FSO_GSM_TYPE_IPDP_HANDLER (fso_gsm_ipdp_handler_get_type ())
#define FSO_GSM_IPDP_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_IPDP_HANDLER, FsoGsmIPdpHandler))
#define FSO_GSM_IS_IPDP_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_IPDP_HANDLER))
#define FSO_GSM_IPDP_HANDLER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FSO_GSM_TYPE_IPDP_HANDLER, FsoGsmIPdpHandlerIface))

typedef struct _FsoGsmIPdpHandler FsoGsmIPdpHandler;
typedef struct _FsoGsmIPdpHandlerIface FsoGsmIPdpHandlerIface;

#define FSO_GSM_TYPE_ROUTE_INFO (fso_gsm_route_info_get_type ())
#define FSO_GSM_ROUTE_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_ROUTE_INFO, FsoGsmRouteInfo))
#define FSO_GSM_ROUTE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_ROUTE_INFO, FsoGsmRouteInfoClass))
#define FSO_GSM_IS_ROUTE_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_ROUTE_INFO))
#define FSO_GSM_IS_ROUTE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_ROUTE_INFO))
#define FSO_GSM_ROUTE_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_ROUTE_INFO, FsoGsmRouteInfoClass))

typedef struct _FsoGsmRouteInfo FsoGsmRouteInfo;
typedef struct _FsoGsmRouteInfoClass FsoGsmRouteInfoClass;

#define FSO_GSM_TYPE_ABSTRACT_AT_COMMAND (fso_gsm_abstract_at_command_get_type ())
#define FSO_GSM_ABSTRACT_AT_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_ABSTRACT_AT_COMMAND, FsoGsmAbstractAtCommand))
#define FSO_GSM_ABSTRACT_AT_COMMAND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_ABSTRACT_AT_COMMAND, FsoGsmAbstractAtCommandClass))
#define FSO_GSM_IS_ABSTRACT_AT_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_ABSTRACT_AT_COMMAND))
#define FSO_GSM_IS_ABSTRACT_AT_COMMAND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_ABSTRACT_AT_COMMAND))
#define FSO_GSM_ABSTRACT_AT_COMMAND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_ABSTRACT_AT_COMMAND, FsoGsmAbstractAtCommandClass))

typedef struct _FsoGsmAbstractAtCommand FsoGsmAbstractAtCommand;
typedef struct _FsoGsmAbstractAtCommandClass FsoGsmAbstractAtCommandClass;

#define FSO_GSM_TYPE_SIMPLE_AT_COMMAND (fso_gsm_simple_at_command_get_type ())
#define FSO_GSM_SIMPLE_AT_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_SIMPLE_AT_COMMAND, FsoGsmSimpleAtCommand))
#define FSO_GSM_SIMPLE_AT_COMMAND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_SIMPLE_AT_COMMAND, FsoGsmSimpleAtCommandClass))
#define FSO_GSM_IS_SIMPLE_AT_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_SIMPLE_AT_COMMAND))
#define FSO_GSM_IS_SIMPLE_AT_COMMAND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_SIMPLE_AT_COMMAND))
#define FSO_GSM_SIMPLE_AT_COMMAND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_SIMPLE_AT_COMMAND, FsoGsmSimpleAtCommandClass))

typedef struct _FsoGsmSimpleAtCommand FsoGsmSimpleAtCommand;
typedef struct _FsoGsmSimpleAtCommandClass FsoGsmSimpleAtCommandClass;

#define FSO_GSM_TYPE_PLUS_CIMI (fso_gsm_plus_cimi_get_type ())
#define FSO_GSM_PLUS_CIMI(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_PLUS_CIMI, FsoGsmPlusCIMI))
#define FSO_GSM_PLUS_CIMI_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_PLUS_CIMI, FsoGsmPlusCIMIClass))
#define FSO_GSM_IS_PLUS_CIMI(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_PLUS_CIMI))
#define FSO_GSM_IS_PLUS_CIMI_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_PLUS_CIMI))
#define FSO_GSM_PLUS_CIMI_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_PLUS_CIMI, FsoGsmPlusCIMIClass))

typedef struct _FsoGsmPlusCIMI FsoGsmPlusCIMI;
typedef struct _FsoGsmPlusCIMIClass FsoGsmPlusCIMIClass;
typedef struct _FsoGsmAbstractAtCommandPrivate FsoGsmAbstractAtCommandPrivate;
typedef struct _FsoGsmSimpleAtCommandPrivate FsoGsmSimpleAtCommandPrivate;
typedef struct _fso_gsm_at_sms_handler_retrieveImsiFromSIMData fso_gsm_at_sms_handler_retrieveImsiFromSIMData;

#define FSO_GSM_TYPE_PLUS_CMGL (fso_gsm_plus_cmgl_get_type ())
#define FSO_GSM_PLUS_CMGL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_PLUS_CMGL, FsoGsmPlusCMGL))
#define FSO_GSM_PLUS_CMGL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_PLUS_CMGL, FsoGsmPlusCMGLClass))
#define FSO_GSM_IS_PLUS_CMGL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_PLUS_CMGL))
#define FSO_GSM_IS_PLUS_CMGL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_PLUS_CMGL))
#define FSO_GSM_PLUS_CMGL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_PLUS_CMGL, FsoGsmPlusCMGLClass))

typedef struct _FsoGsmPlusCMGL FsoGsmPlusCMGL;
typedef struct _FsoGsmPlusCMGLClass FsoGsmPlusCMGLClass;

#define FSO_GSM_PLUS_CMGL_TYPE_MODE (fso_gsm_plus_cmgl_mode_get_type ())
typedef struct _FsoGsmPlusCMGLPrivate FsoGsmPlusCMGLPrivate;

#define TYPE_WRAP_SMS (wrap_sms_get_type ())
#define WRAP_SMS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_WRAP_SMS, WrapSms))
#define WRAP_SMS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_WRAP_SMS, WrapSmsClass))
#define IS_WRAP_SMS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_WRAP_SMS))
#define IS_WRAP_SMS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_WRAP_SMS))
#define WRAP_SMS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_WRAP_SMS, WrapSmsClass))

typedef struct _WrapSms WrapSms;
typedef struct _WrapSmsClass WrapSmsClass;
typedef struct _WrapSmsPrivate WrapSmsPrivate;
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _wrap_sms_unref0(var) ((var == NULL) ? NULL : (var = (wrap_sms_unref (var), NULL)))
typedef struct _fso_gsm_at_sms_handler_fillStorageWithMessageFromSIMData fso_gsm_at_sms_handler_fillStorageWithMessageFromSIMData;

#define FSO_GSM_TYPE_PLUS_CMGR (fso_gsm_plus_cmgr_get_type ())
#define FSO_GSM_PLUS_CMGR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_PLUS_CMGR, FsoGsmPlusCMGR))
#define FSO_GSM_PLUS_CMGR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_PLUS_CMGR, FsoGsmPlusCMGRClass))
#define FSO_GSM_IS_PLUS_CMGR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_PLUS_CMGR))
#define FSO_GSM_IS_PLUS_CMGR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_PLUS_CMGR))
#define FSO_GSM_PLUS_CMGR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_PLUS_CMGR, FsoGsmPlusCMGRClass))

typedef struct _FsoGsmPlusCMGR FsoGsmPlusCMGR;
typedef struct _FsoGsmPlusCMGRClass FsoGsmPlusCMGRClass;
typedef struct _FsoGsmPlusCMGRPrivate FsoGsmPlusCMGRPrivate;
typedef struct _fso_gsm_at_sms_handler_readSmsMessageFromSIMData fso_gsm_at_sms_handler_readSmsMessageFromSIMData;

#define FSO_GSM_TYPE_PLUS_CNMA (fso_gsm_plus_cnma_get_type ())
#define FSO_GSM_PLUS_CNMA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_GSM_TYPE_PLUS_CNMA, FsoGsmPlusCNMA))
#define FSO_GSM_PLUS_CNMA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_GSM_TYPE_PLUS_CNMA, FsoGsmPlusCNMAClass))
#define FSO_GSM_IS_PLUS_CNMA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_GSM_TYPE_PLUS_CNMA))
#define FSO_GSM_IS_PLUS_CNMA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_GSM_TYPE_PLUS_CNMA))
#define FSO_GSM_PLUS_CNMA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_GSM_TYPE_PLUS_CNMA, FsoGsmPlusCNMAClass))

typedef struct _FsoGsmPlusCNMA FsoGsmPlusCNMA;
typedef struct _FsoGsmPlusCNMAClass FsoGsmPlusCNMAClass;
typedef struct _fso_gsm_at_sms_handler_acknowledgeSmsMessageData fso_gsm_at_sms_handler_acknowledgeSmsMessageData;

struct _FsoGsmISmsStorageIface {
	GTypeInterface parent_iface;
	void (*clean) (FsoGsmISmsStorage* self);
	gint (*addSms) (FsoGsmISmsStorage* self, struct sms* message);
	GeeArrayList* (*keys) (FsoGsmISmsStorage* self);
	void (*message) (FsoGsmISmsStorage* self, const gchar* key, gint index, FreeSmartphoneGSMSIMMessage* result);
	FreeSmartphoneGSMSIMMessage* (*messagebook) (FsoGsmISmsStorage* self, int* result_length1);
	guint16 (*lastReferenceNumber) (FsoGsmISmsStorage* self);
	guint16 (*increasingReferenceNumber) (FsoGsmISmsStorage* self);
	void (*storeTransactionIndizesForSentMessage) (FsoGsmISmsStorage* self, GeeArrayList* hexpdus);
	gint (*confirmReceivedMessage) (FsoGsmISmsStorage* self, gint netreference);
};

struct _FsoGsmSmsHandlerIface {
	GTypeInterface parent_iface;
	void (*handleIncomingSmsOnSim) (FsoGsmSmsHandler* self, guint index, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*handleIncomingSmsOnSim_finish) (FsoGsmSmsHandler* self, GAsyncResult* _res_);
	void (*handleIncomingSms) (FsoGsmSmsHandler* self, const gchar* hexpdu, gint tpdulen, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*handleIncomingSms_finish) (FsoGsmSmsHandler* self, GAsyncResult* _res_);
	void (*handleIncomingSmsReport) (FsoGsmSmsHandler* self, const gchar* hexpdu, gint tpdulen, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*handleIncomingSmsReport_finish) (FsoGsmSmsHandler* self, GAsyncResult* _res_);
	guint16 (*lastReferenceNumber) (FsoGsmSmsHandler* self);
	guint16 (*nextReferenceNumber) (FsoGsmSmsHandler* self);
	GeeArrayList* (*formatTextMessage) (FsoGsmSmsHandler* self, const gchar* number, const gchar* contents, gboolean requestReport);
	void (*storeTransactionIndizesForSentMessage) (FsoGsmSmsHandler* self, GeeArrayList* hexpdus);
	FsoGsmISmsStorage* (*get_storage) (FsoGsmSmsHandler* self);
	void (*set_storage) (FsoGsmSmsHandler* self, FsoGsmISmsStorage* value);
};

struct _FsoGsmAbstractSmsHandler {
	FsoFrameworkAbstractObject parent_instance;
	FsoGsmAbstractSmsHandlerPrivate * priv;
};

struct _FsoGsmAbstractSmsHandlerClass {
	FsoFrameworkAbstractObjectClass parent_class;
	void (*retrieveImsiFromSIM) (FsoGsmAbstractSmsHandler* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	gchar* (*retrieveImsiFromSIM_finish) (FsoGsmAbstractSmsHandler* self, GAsyncResult* _res_);
	void (*fillStorageWithMessageFromSIM) (FsoGsmAbstractSmsHandler* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*fillStorageWithMessageFromSIM_finish) (FsoGsmAbstractSmsHandler* self, GAsyncResult* _res_);
	void (*readSmsMessageFromSIM) (FsoGsmAbstractSmsHandler* self, guint index, GAsyncReadyCallback _callback_, gpointer _user_data_);
	gboolean (*readSmsMessageFromSIM_finish) (FsoGsmAbstractSmsHandler* self, GAsyncResult* _res_, gchar** hexpdu, gint* tpdulen);
	void (*acknowledgeSmsMessage) (FsoGsmAbstractSmsHandler* self, gint id, GAsyncReadyCallback _callback_, gpointer _user_data_);
	gboolean (*acknowledgeSmsMessage_finish) (FsoGsmAbstractSmsHandler* self, GAsyncResult* _res_);
};

struct _FsoGsmAtSmsHandler {
	FsoGsmAbstractSmsHandler parent_instance;
	FsoGsmAtSmsHandlerPrivate * priv;
};

struct _FsoGsmAtSmsHandlerClass {
	FsoGsmAbstractSmsHandlerClass parent_class;
};

struct _FsoGsmChannelIface {
	GTypeInterface parent_iface;
	void (*injectResponse) (FsoGsmChannel* self, const gchar* response);
	void (*suspend) (FsoGsmChannel* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	gboolean (*suspend_finish) (FsoGsmChannel* self, GAsyncResult* _res_);
	void (*resume) (FsoGsmChannel* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	gboolean (*resume_finish) (FsoGsmChannel* self, GAsyncResult* _res_);
};

typedef enum  {
	FSO_GSM_MODEM_STATUS_UNKNOWN,
	FSO_GSM_MODEM_STATUS_CLOSED,
	FSO_GSM_MODEM_STATUS_INITIALIZING,
	FSO_GSM_MODEM_STATUS_ALIVE_NO_SIM,
	FSO_GSM_MODEM_STATUS_ALIVE_SIM_LOCKED,
	FSO_GSM_MODEM_STATUS_ALIVE_SIM_UNLOCKED,
	FSO_GSM_MODEM_STATUS_ALIVE_SIM_READY,
	FSO_GSM_MODEM_STATUS_ALIVE_REGISTERED,
	FSO_GSM_MODEM_STATUS_SUSPENDING,
	FSO_GSM_MODEM_STATUS_SUSPENDED,
	FSO_GSM_MODEM_STATUS_RESUMING,
	FSO_GSM_MODEM_STATUS_CLOSING
} FsoGsmModemStatus;

typedef enum  {
	FSO_GSM_MODEM_NETWORK_STATUS_UNKNOWN,
	FSO_GSM_MODEM_NETWORK_STATUS_UNREGISTERED,
	FSO_GSM_MODEM_NETWORK_STATUS_SEARCHING,
	FSO_GSM_MODEM_NETWORK_STATUS_REGISTERED
} FsoGsmModemNetworkStatus;

struct _FsoGsmAtCommandQueueCommandIface {
	GTypeInterface parent_iface;
	guint (*get_retry) (FsoGsmAtCommandQueueCommand* self);
	guint (*get_timeout) (FsoGsmAtCommandQueueCommand* self);
	gchar* (*get_prefix) (FsoGsmAtCommandQueueCommand* self);
	gchar* (*get_postfix) (FsoGsmAtCommandQueueCommand* self);
	gboolean (*is_valid_prefix) (FsoGsmAtCommandQueueCommand* self, const gchar* line);
};

typedef enum  {
	FSO_GSM_AT_COMMAND_ERROR_UNABLE_TO_PARSE
} FsoGsmAtCommandError;
#define FSO_GSM_AT_COMMAND_ERROR fso_gsm_at_command_error_quark ()
typedef enum  {
	FSO_GSM_CONSTANTS_AT_RESPONSE_VALID = 0,
	FSO_GSM_CONSTANTS_AT_RESPONSE_OK = 1,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CONNECT = 2,
	FSO_GSM_CONSTANTS_AT_RESPONSE_UNEXPECTED_LENGTH = 501,
	FSO_GSM_CONSTANTS_AT_RESPONSE_UNABLE_TO_PARSE = 502,
	FSO_GSM_CONSTANTS_AT_RESPONSE_ERROR = 503,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_START = 1000,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_000_PHONE_FAILURE = 1000,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_001_NO_CONNECTION_TO_PHONE = 1001,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_002_PHONE_ADAPTER_LINK_RESERVED = 1002,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_003_OPERATION_NOT_ALLOWED = 1003,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_004_OPERATION_NOT_SUPPORTED = 1004,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_005_PH_SIM_PIN_REQUIRED = 1005,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_006_PH_FSIM_PIN_REQUIRED = 1006,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_007_PH_FSIM_PUK_REQUIRED = 1007,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_010_SIM_NOT_INSERTED = 1010,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_011_SIM_PIN_REQUIRED = 1011,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_012_SIM_PUK_REQUIRED = 1012,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_013_SIM_FAILURE = 1013,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_014_SIM_BUSY = 1014,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_015_SIM_WRONG = 1015,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_016_INCORRECT_PASSWORD = 1016,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_017_SIM_PIN2_REQUIRED = 1017,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_018_SIM_PUK2_REQUIRED = 1018,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_020_MEMORY_FULL = 1020,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_021_INVALID_INDEX = 1021,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_022_NOT_FOUND = 1022,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_023_MEMORY_FAILURE = 1023,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_024_TEXT_STRING_TOO_LONG = 1024,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_025_INVALID_CHARACTERS_IN_TEXT_STRING = 1025,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_026_DIAL_STRING_TOO_LONG = 1026,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_027_INVALID_CHARACTERS_IN_DIAL_STRING = 1027,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_030_NO_NETWORK_SERVICE = 1030,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_031_NETWORK_TIMEOUT = 1031,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_032_NETWORK_NOT_ALLOWED_EMERGENCY_CALLS_ONLY = 1032,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_040_NETWORK_PERSONALIZATION_PIN_REQUIRED = 1040,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_041_NETWORK_PERSONALIZATION_PUK_REQUIRED = 1041,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_042_NETWORK_SUBSET_PERSONALIZATION_PIN_REQUIRED = 1042,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_043_NETWORK_SUBSET_PERSONALIZATION_PUK_REQUIRED = 1043,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_044_SERVICE_PROVIDER_PERSONALIZATION_PIN_REQUIRED = 1044,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_045_SERVICE_PROVIDER_PERSONALIZATION_PUK_REQUIRED = 1045,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_046_CORPORATE_PERSONALIZATION_PIN_REQUIRED = 1046,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_047_CORPORATE_PERSONALIZATION_PUK_REQUIRED = 1047,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_048_PH_SIM_PUK_REQUIRED = 1048,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_100_UNKNOWN_ERROR = 1100,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_103_GPRS_ILLEGAL_MS = 1103,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_106_GPRS_ILLEGAL_ME = 1106,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_107_GPRS_SERVICES_NOT_ALLOWED = 1107,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_111_GPRS_PLMN_NOT_ALLOWED = 1111,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_112_GPRS_LOCATION_AREA_NOT_ALLOWED = 1112,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_113_GPRS_ROAMING_NOT_ALLOWED_IN_THIS_LOCATION_AREA = 1113,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_126_GPRS_OPERATION_TEMPORARY_NOT_ALLOWED = 1126,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_132_GPRS_SERVICE_OPERATION_NOT_SUPPORTED = 1132,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_133_GPRS_REQUESTED_SERVICE_OPTION_NOT_SUBSCRIBED = 1133,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_134_GPRS_SERVICE_OPTION_TEMPORARY_OUT_OF_ORDER = 1134,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_148_GPRS_UNSPECIFIED_ERROR = 1148,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_149_GPRS_PDP_AUTHENTICATION_FAILURE = 1149,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_150_GPRS_INVALID_MOBILE_CLASS = 1150,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_256_OPERATION_TEMPORARILY_NOT_ALLOWED = 1256,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_257_CALL_BARRED = 1257,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_258_PHONE_IS_BUSY = 1258,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_259_USER_ABORT = 1259,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_260_INVALID_DIAL_STRING = 1260,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_261_SS_NOT_EXECUTED = 1261,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_262_SIM_BLOCKED = 1262,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_263_INVALID_BLOCK = 1263,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_265_BUSY_TRY_AGAIN = 1265,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_512_FAILED_TO_ABORT_COMMAND = 1512,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_513_ACM_RESET_NEEDED = 1513,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_514_SIM_APPLICATION_TOOLKIT_BUSY = 1514,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CME_ERROR_772_SIM_POWERED_DOWN = 1772,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_START = 2000,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_001_UNASSIGNED_NUMBER = 2001,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_008_OPERATOR_DETERMINED_BARRING = 2008,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_010_CALL_BARED = 2010,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_021_SHORT_MESSAGE_TRANSFER_REJECTED = 2021,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_027_DESTINATION_OUT_OF_SERVICE = 2027,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_028_UNIDENTIFIED_SUBSCRIBER = 2028,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_029_FACILITY_REJECTED = 2029,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_030_UNKNOWN_SUBSCRIBER = 2030,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_038_NETWORK_OUT_OF_ORDER = 2038,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_041_TEMPORARY_FAILURE = 2041,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_042_CONGESTION = 2042,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_047_RECOURCES_UNAVAILABLE = 2047,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_050_REQUESTED_FACILITY_NOT_SUBSCRIBED = 2050,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_069_REQUESTED_FACILITY_NOT_IMPLEMENTED = 2069,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_081_INVALID_SHORT_MESSAGE_TRANSFER_REFERENCE_VALUE = 2081,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_095_INVALID_MESSAGE_UNSPECIFIED = 2095,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_096_INVALID_MANDATORY_INFORMATION = 2096,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_097_MESSAGE_TYPE_NON_EXISTENT_OR_NOT_IMPLEMENTED = 2097,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_098_MESSAGE_NOT_COMPATIBLE_WITH_SHORT_MESSAGE_PROTOCOL = 2098,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_099_INFORMATION_ELEMENT_NON_EXISTENT_OR_NOT_IMPLEMENTED = 2099,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_111_PROTOCOL_ERROR_UNSPECIFIED = 2111,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_127_INTERNETWORKING_UNSPECIFIED = 2127,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_128_TELEMATIC_INTERNETWORKING_NOT_SUPPORTED = 2128,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_129_SHORT_MESSAGE_TYPE_0_NOT_SUPPORTED = 2129,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_130_CANNOT_REPLACE_SHORT_MESSAGE = 2130,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_143_UNSPECIFIED_TP_PID_ERROR = 2143,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_144_DATA_CODE_SCHEME_NOT_SUPPORTED = 2144,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_145_MESSAGE_CLASS_NOT_SUPPORTED = 2145,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_159_UNSPECIFIED_TP_DCS_ERROR = 2159,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_160_COMMAND_CANNOT_BE_ACTIONED = 2160,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_161_COMMAND_UNSUPPORTED = 2161,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_175_UNSPECIFIED_TP_COMMAND_ERROR = 2175,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_176_TPDU_NOT_SUPPORTED = 2176,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_192_SC_BUSY = 2192,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_193_NO_SC_SUBSCRIPTION = 2193,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_194_SC_SYSTEM_FAILURE = 2194,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_195_INVALID_SME_ADDRESS = 2195,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_196_DESTINATION_SME_BARRED = 2196,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_197_SM_REJECTED_DUPLICATE_SM = 2197,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_198_TP_VPF_NOT_SUPPORTED = 2198,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_199_TP_VP_NOT_SUPPORTED = 2199,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_208_D0_SIM_SMS_STORAGE_FULL = 2208,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_209_NO_SMS_STORAGE_CAPABILITY_IN_SIM = 2209,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_210_ERROR_IN_MS = 2210,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_211_MEMORY_CAPACITY_EXCEEDED = 2211,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_212_SIM_APPLICATION_TOOLKIT_BUSY = 2212,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_213_SIM_DATA_DOWNLOAD_ERROR = 2213,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_255_UNSPECIFIED_ERROR_CAUSE = 2255,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_300_ME_FAILURE = 2300,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_301_SMS_SERVICE_OF_ME_RESERVED = 2301,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_302_OPERATION_NOT_ALLOWED = 2302,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_303_OPERATION_NOT_SUPPORTED = 2303,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_304_INVALID_PDU_MODE_PARAMETER = 2304,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_305_INVALID_TEXT_MODE_PARAMETER = 2305,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_310_SIM_NOT_INSERTED = 2310,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_311_SIM_PIN_REQUIRED = 2311,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_312_PH_SIM_PIN_REQUIRED = 2312,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_313_SIM_FAILURE = 2313,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_314_SIM_BUSY = 2314,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_315_SIM_WRONG = 2315,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_316_SIM_PUK_REQUIRED = 2316,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_317_SIM_PIN2_REQUIRED = 2317,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_318_SIM_PUK2_REQUIRED = 2318,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_320_MEMORY_FAILURE = 2320,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_321_INVALID_MEMORY_INDEX = 2321,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_322_MEMORY_FULL = 2322,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_330_SMSC_ADDRESS_UNKNOWN = 2330,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_331_NO_NETWORK_SERVICE = 2331,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_332_NETWORK_TIMEOUT = 2332,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_340_NO_CNMA_EXPECTED = 2340,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_500_UNKNOWN_ERROR = 2500,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_512_FAILED_TO_ABORT_COMMAND = 2512,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_513_ACM_RESET_NEEDED = 2513,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_514_INVALID_STATUS = 2514,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_515_DEVICE_BUSY_OR_INVALID_CHARACTER_IN_STRING = 2515,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_516_INVALID_LENGTH = 2516,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_517_INVALID_CHARACTER_IN_PDU = 2517,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_518_INVALID_PARAMETER = 2518,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_519_INVALID_LENGTH_OR_CHARACTER = 2519,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_520_INVALID_CHARACTER_IN_TEXT = 2520,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_521_TIMER_EXPIRED = 2521,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_522_OPERATION_TEMPORARY_NOT_ALLOWED = 2522,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_532_SIM_NOT_READY = 2532,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_534_CELL_BROADCAST_ERROR_UNKNOWN = 2534,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_535_PROTOCOL_STACK_BUSY = 2535,
	FSO_GSM_CONSTANTS_AT_RESPONSE_CMS_ERROR_538_INVALID_PARAMETER = 2538,
	FSO_GSM_CONSTANTS_AT_RESPONSE_EXT_ERROR_START = 3000,
	FSO_GSM_CONSTANTS_AT_RESPONSE_EXT_ERROR_0_INVALID_PARAMETERR = 3000
} FsoGsmConstantsAtResponse;

struct _FsoGsmAtCommandIface {
	GTypeInterface parent_iface;
	guint (*get_timeout) (FsoGsmAtCommand* self);
	guint (*get_retry) (FsoGsmAtCommand* self);
	gchar* (*get_prefix) (FsoGsmAtCommand* self);
	gchar* (*get_postfix) (FsoGsmAtCommand* self);
	gboolean (*is_valid_prefix) (FsoGsmAtCommand* self, const gchar* line);
	void (*parse) (FsoGsmAtCommand* self, const gchar* response, GError** error);
	void (*parseMulti) (FsoGsmAtCommand* self, gchar** response, int response_length1, GError** error);
	void (*parseTest) (FsoGsmAtCommand* self, const gchar* response, GError** error);
	gchar* (*encodeString) (FsoGsmAtCommand* self, const gchar* str);
	gchar* (*decodeString) (FsoGsmAtCommand* self, const gchar* str);
	FsoGsmConstantsAtResponse (*validate) (FsoGsmAtCommand* self, gchar** response, int response_length1);
	FsoGsmConstantsAtResponse (*validateTest) (FsoGsmAtCommand* self, gchar** response, int response_length1);
	FsoGsmConstantsAtResponse (*validateUrc) (FsoGsmAtCommand* self, const gchar* response);
	FsoGsmConstantsAtResponse (*validateUrcPdu) (FsoGsmAtCommand* self, gchar** response, int response_length1);
	FsoGsmConstantsAtResponse (*validateOk) (FsoGsmAtCommand* self, gchar** response, int response_length1);
	FsoGsmConstantsAtResponse (*validateMulti) (FsoGsmAtCommand* self, gchar** response, int response_length1);
};

struct _FsoGsmCallHandlerIface {
	GTypeInterface parent_iface;
	void (*handleIncomingCall) (FsoGsmCallHandler* self, FsoGsmCallInfo* call_info);
	void (*handleConnectingCall) (FsoGsmCallHandler* self, FsoGsmCallInfo* call_info);
	void (*handleEndingCall) (FsoGsmCallHandler* self, FsoGsmCallInfo* call_info);
	void (*addSupplementaryInformation) (FsoGsmCallHandler* self, const gchar* direction, const gchar* info);
	void (*activate) (FsoGsmCallHandler* self, gint id, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*activate_finish) (FsoGsmCallHandler* self, GAsyncResult* _res_, GError** error);
	void (*initiate) (FsoGsmCallHandler* self, const gchar* number, const gchar* ctype, GAsyncReadyCallback _callback_, gpointer _user_data_);
	gint (*initiate_finish) (FsoGsmCallHandler* self, GAsyncResult* _res_, GError** error);
	void (*hold) (FsoGsmCallHandler* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*hold_finish) (FsoGsmCallHandler* self, GAsyncResult* _res_, GError** error);
	void (*release) (FsoGsmCallHandler* self, gint id, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*release_finish) (FsoGsmCallHandler* self, GAsyncResult* _res_, GError** error);
	void (*releaseAll) (FsoGsmCallHandler* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*releaseAll_finish) (FsoGsmCallHandler* self, GAsyncResult* _res_, GError** error);
};

struct _FsoGsmPhonebookHandlerIface {
	GTypeInterface parent_iface;
	void (*syncWithSim) (FsoGsmPhonebookHandler* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*syncWithSim_finish) (FsoGsmPhonebookHandler* self, GAsyncResult* _res_);
	FsoGsmPhonebookStorage* (*get_storage) (FsoGsmPhonebookHandler* self);
	void (*set_storage) (FsoGsmPhonebookHandler* self, FsoGsmPhonebookStorage* value);
};

struct _FsoGsmWatchDogIface {
	GTypeInterface parent_iface;
	void (*check) (FsoGsmWatchDog* self);
	void (*resetUnlockMarker) (FsoGsmWatchDog* self);
};

struct _FsoGsmIPdpHandlerIface {
	GTypeInterface parent_iface;
	void (*activate) (FsoGsmIPdpHandler* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*activate_finish) (FsoGsmIPdpHandler* self, GAsyncResult* _res_, GError** error);
	void (*deactivate) (FsoGsmIPdpHandler* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*deactivate_finish) (FsoGsmIPdpHandler* self, GAsyncResult* _res_, GError** error);
	void (*statusUpdate) (FsoGsmIPdpHandler* self, const gchar* status, GHashTable* properties, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*statusUpdate_finish) (FsoGsmIPdpHandler* self, GAsyncResult* _res_);
	void (*connectedWithNewDefaultRoute) (FsoGsmIPdpHandler* self, FsoGsmRouteInfo* route, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*connectedWithNewDefaultRoute_finish) (FsoGsmIPdpHandler* self, GAsyncResult* _res_);
	void (*disconnected) (FsoGsmIPdpHandler* self);
	void (*syncStatus) (FsoGsmIPdpHandler* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*syncStatus_finish) (FsoGsmIPdpHandler* self, GAsyncResult* _res_);
	FreeSmartphoneGSMContextStatus (*get_status) (FsoGsmIPdpHandler* self);
	void (*set_status) (FsoGsmIPdpHandler* self, FreeSmartphoneGSMContextStatus value);
	GHashTable* (*get_properties) (FsoGsmIPdpHandler* self);
	void (*set_properties) (FsoGsmIPdpHandler* self, GHashTable* value);
};

struct _FsoGsmModemIface {
	GTypeInterface parent_iface;
	void (*open) (FsoGsmModem* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	gboolean (*open_finish) (FsoGsmModem* self, GAsyncResult* _res_);
	void (*close) (FsoGsmModem* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*close_finish) (FsoGsmModem* self, GAsyncResult* _res_);
	void (*suspend) (FsoGsmModem* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	gboolean (*suspend_finish) (FsoGsmModem* self, GAsyncResult* _res_);
	void (*resume) (FsoGsmModem* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	gboolean (*resume_finish) (FsoGsmModem* self, GAsyncResult* _res_);
	void (*injectResponse) (FsoGsmModem* self, const gchar* command, const gchar* channel, GError** error);
	void (*setFunctionality) (FsoGsmModem* self, const gchar* level, gboolean autoregister, const gchar* pin, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*setFunctionality_finish) (FsoGsmModem* self, GAsyncResult* _res_, GError** error);
	void (*registerChannel) (FsoGsmModem* self, const gchar* name, FsoGsmChannel* channel);
	void (*advanceToState) (FsoGsmModem* self, FsoGsmModemStatus status, gboolean force);
	void (*advanceNetworkState) (FsoGsmModem* self, FsoGsmModemNetworkStatus status);
	FsoGsmAtCommandSequence* (*atCommandSequence) (FsoGsmModem* self, const gchar* channel, const gchar* purpose);
	gpointer (*createMediator) (FsoGsmModem* self, GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, GError** error);
	gpointer (*createAtCommand) (FsoGsmModem* self, GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, const gchar* command);
	gpointer (*theDevice) (FsoGsmModem* self, GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func);
	gchar* (*allocateDataPort) (FsoGsmModem* self);
	void (*releaseDataPort) (FsoGsmModem* self);
	void (*processAtCommandAsync) (FsoGsmModem* self, FsoGsmAtCommand* command, const gchar* request, gint retries, GAsyncReadyCallback _callback_, gpointer _user_data_);
	gchar** (*processAtCommandAsync_finish) (FsoGsmModem* self, GAsyncResult* _res_, int* result_length1);
	void (*processAtPduCommandAsync) (FsoGsmModem* self, FsoGsmAtCommand* command, const gchar* request, gint retries, GAsyncReadyCallback _callback_, gpointer _user_data_);
	gchar** (*processAtPduCommandAsync_finish) (FsoGsmModem* self, GAsyncResult* _res_, int* result_length1);
	void (*sendAtCommand) (FsoGsmModem* self, FsoGsmAtCommand* command, const gchar* request, gint retries);
	FsoGsmChannel* (*channel) (FsoGsmModem* self, const gchar* category);
	FsoGsmModemStatus (*status) (FsoGsmModem* self);
	FsoGsmModemNetworkStatus (*network_status) (FsoGsmModem* self);
	FreeSmartphoneGSMDeviceStatus (*externalStatus) (FsoGsmModem* self);
	FsoGsmModemData* (*data) (FsoGsmModem* self);
	void (*registerAtCommandSequence) (FsoGsmModem* self, const gchar* channel, const gchar* purpose, FsoGsmAtCommandSequence* sequence);
	gboolean (*isAlive) (FsoGsmModem* self);
	GObject* (*get_parent) (FsoGsmModem* self);
	void (*set_parent) (FsoGsmModem* self, GObject* value);
	FsoGsmCallHandler* (*get_callhandler) (FsoGsmModem* self);
	void (*set_callhandler) (FsoGsmModem* self, FsoGsmCallHandler* value);
	FsoGsmSmsHandler* (*get_smshandler) (FsoGsmModem* self);
	void (*set_smshandler) (FsoGsmModem* self, FsoGsmSmsHandler* value);
	FsoGsmPhonebookHandler* (*get_pbhandler) (FsoGsmModem* self);
	void (*set_pbhandler) (FsoGsmModem* self, FsoGsmPhonebookHandler* value);
	FsoGsmWatchDog* (*get_watchdog) (FsoGsmModem* self);
	void (*set_watchdog) (FsoGsmModem* self, FsoGsmWatchDog* value);
	FsoGsmIPdpHandler* (*get_pdphandler) (FsoGsmModem* self);
	void (*set_pdphandler) (FsoGsmModem* self, FsoGsmIPdpHandler* value);
};

struct _FsoGsmAbstractAtCommand {
	GObject parent_instance;
	FsoGsmAbstractAtCommandPrivate * priv;
	GRegex* re;
	GRegex* tere;
	GMatchInfo* mi;
	gchar** prefix;
	gint prefix_length1;
	gint length;
};

struct _FsoGsmAbstractAtCommandClass {
	GObjectClass parent_class;
	void (*parse) (FsoGsmAbstractAtCommand* self, const gchar* response, GError** error);
	void (*parseTest) (FsoGsmAbstractAtCommand* self, const gchar* response, GError** error);
	void (*parseMulti) (FsoGsmAbstractAtCommand* self, gchar** response, int response_length1, GError** error);
	FsoGsmConstantsAtResponse (*validateOk) (FsoGsmAbstractAtCommand* self, gchar** response, int response_length1);
	FsoGsmConstantsAtResponse (*validate) (FsoGsmAbstractAtCommand* self, gchar** response, int response_length1);
	FsoGsmConstantsAtResponse (*validateTest) (FsoGsmAbstractAtCommand* self, gchar** response, int response_length1);
	FsoGsmConstantsAtResponse (*validateMulti) (FsoGsmAbstractAtCommand* self, gchar** response, int response_length1);
	FsoGsmConstantsAtResponse (*validateUrc) (FsoGsmAbstractAtCommand* self, const gchar* response);
	FsoGsmConstantsAtResponse (*validateUrcPdu) (FsoGsmAbstractAtCommand* self, gchar** response, int response_length1);
	guint (*get_timeout) (FsoGsmAbstractAtCommand* self);
	guint (*get_retry) (FsoGsmAbstractAtCommand* self);
	gchar* (*get_prefix) (FsoGsmAbstractAtCommand* self);
	gchar* (*get_postfix) (FsoGsmAbstractAtCommand* self);
};

struct _FsoGsmSimpleAtCommand {
	FsoGsmAbstractAtCommand parent_instance;
	FsoGsmSimpleAtCommandPrivate * priv;
	gpointer value;
	gchar* righthandside;
	gint min;
	gint max;
};

struct _FsoGsmSimpleAtCommandClass {
	FsoGsmAbstractAtCommandClass parent_class;
};

struct _fso_gsm_at_sms_handler_retrieveImsiFromSIMData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	FsoGsmAtSmsHandler* self;
	gchar* result;
	FsoGsmModem* _tmp0_;
	gpointer _tmp1_;
	FsoGsmPlusCIMI* cimi;
	FsoGsmModem* _tmp2_;
	FsoGsmPlusCIMI* _tmp3_;
	FsoGsmPlusCIMI* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gint _tmp7_;
	gchar** _tmp8_;
	gchar** _tmp9_;
	gint _tmp9__length1;
	gchar** response;
	gint response_length1;
	gint _response_size_;
	FsoGsmPlusCIMI* _tmp10_;
	gchar** _tmp11_;
	gint _tmp11__length1;
	FsoGsmConstantsAtResponse _tmp12_;
	FsoFrameworkLogger* _tmp13_;
	gchar* _tmp14_;
	FsoGsmPlusCIMI* _tmp15_;
	gconstpointer _tmp16_;
	gchar* _tmp17_;
};

typedef enum  {
	FSO_GSM_PLUS_CMGL_MODE_INVALID = -1,
	FSO_GSM_PLUS_CMGL_MODE_REC_UNREAD = 0,
	FSO_GSM_PLUS_CMGL_MODE_REC_READ = 1,
	FSO_GSM_PLUS_CMGL_MODE_STO_UNSENT = 2,
	FSO_GSM_PLUS_CMGL_MODE_STO_SENT = 3,
	FSO_GSM_PLUS_CMGL_MODE_ALL = 4
} FsoGsmPlusCMGLMode;

struct _FsoGsmPlusCMGL {
	FsoGsmAbstractAtCommand parent_instance;
	FsoGsmPlusCMGLPrivate * priv;
	GeeArrayList* messagebook;
};

struct _FsoGsmPlusCMGLClass {
	FsoGsmAbstractAtCommandClass parent_class;
};

struct _WrapSms {
	GTypeInstance parent_instance;
	volatile int ref_count;
	WrapSmsPrivate * priv;
	struct sms* message;
	gint index;
};

struct _WrapSmsClass {
	GTypeClass parent_class;
	void (*finalize) (WrapSms *self);
};

struct _fso_gsm_at_sms_handler_fillStorageWithMessageFromSIMData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	FsoGsmAtSmsHandler* self;
	FsoGsmModem* _tmp0_;
	gpointer _tmp1_;
	FsoGsmPlusCMGL* cmgl;
	FsoGsmModem* _tmp2_;
	FsoGsmPlusCMGL* _tmp3_;
	FsoGsmPlusCMGL* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gint _tmp7_;
	gchar** _tmp8_;
	gchar** _tmp9_;
	gint _tmp9__length1;
	gchar** cmglresponse;
	gint cmglresponse_length1;
	gint _cmglresponse_size_;
	FsoGsmPlusCMGL* _tmp10_;
	gchar** _tmp11_;
	gint _tmp11__length1;
	FsoGsmConstantsAtResponse _tmp12_;
	FsoFrameworkLogger* _tmp13_;
	FsoGsmPlusCMGL* _tmp14_;
	GeeArrayList* _tmp15_;
	GeeArrayList* _tmp16_;
	GeeArrayList* _sms_list;
	GeeArrayList* _tmp17_;
	gint _tmp18_;
	gint _tmp19_;
	gint _sms_size;
	gint _sms_index;
	gint _tmp20_;
	gint _tmp21_;
	gint _tmp22_;
	GeeArrayList* _tmp23_;
	gint _tmp24_;
	gpointer _tmp25_;
	WrapSms* sms;
	FsoGsmISmsStorage* _tmp26_;
	FsoGsmISmsStorage* _tmp27_;
	WrapSms* _tmp28_;
	struct sms* _tmp29_;
	gint _tmp30_;
	gint ret;
	gint _tmp31_;
	FsoGsmISmsStorage* _tmp32_;
	FsoGsmISmsStorage* _tmp33_;
	WrapSms* _tmp34_;
	struct sms* _tmp35_;
	gchar* _tmp36_;
	gchar* _tmp37_;
	FreeSmartphoneGSMSIMMessage _tmp38_;
	FreeSmartphoneGSMSIMMessage _tmp39_;
	FreeSmartphoneGSMSIMMessage msg;
	FsoGsmModem* _tmp40_;
	gpointer _tmp41_;
	FreeSmartphoneGSMSMS* obj;
	FreeSmartphoneGSMSMS* _tmp42_;
	FreeSmartphoneGSMSIMMessage _tmp43_;
	const gchar* _tmp44_;
	FreeSmartphoneGSMSIMMessage _tmp45_;
	const gchar* _tmp46_;
	FreeSmartphoneGSMSIMMessage _tmp47_;
	const gchar* _tmp48_;
};

struct _FsoGsmPlusCMGR {
	FsoGsmAbstractAtCommand parent_instance;
	FsoGsmPlusCMGRPrivate * priv;
	FsoGsmPlusCMGLMode status;
	gchar* hexpdu;
	gint tpdulen;
};

struct _FsoGsmPlusCMGRClass {
	FsoGsmAbstractAtCommandClass parent_class;
};

struct _fso_gsm_at_sms_handler_readSmsMessageFromSIMData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	FsoGsmAtSmsHandler* self;
	guint index;
	gchar* hexpdu;
	gint tpdulen;
	gboolean result;
	gchar* _tmp0_;
	FsoGsmModem* _tmp1_;
	gpointer _tmp2_;
	FsoGsmPlusCMGR* cmd;
	FsoGsmModem* _tmp3_;
	FsoGsmPlusCMGR* _tmp4_;
	FsoGsmPlusCMGR* _tmp5_;
	guint _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gint _tmp9_;
	gchar** _tmp10_;
	gchar** _tmp11_;
	gint _tmp11__length1;
	gchar** response;
	gint response_length1;
	gint _response_size_;
	FsoGsmPlusCMGR* _tmp12_;
	gchar** _tmp13_;
	gint _tmp13__length1;
	FsoGsmConstantsAtResponse _tmp14_;
	FsoFrameworkLogger* _tmp15_;
	guint _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	FsoGsmPlusCMGR* _tmp21_;
	const gchar* _tmp22_;
	gchar* _tmp23_;
	FsoGsmPlusCMGR* _tmp24_;
	gint _tmp25_;
};

struct _fso_gsm_at_sms_handler_acknowledgeSmsMessageData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	FsoGsmAtSmsHandler* self;
	gint id;
	gboolean result;
	FsoGsmModem* _tmp0_;
	gpointer _tmp1_;
	FsoGsmPlusCNMA* cmd;
	FsoGsmModem* _tmp2_;
	FsoGsmPlusCNMA* _tmp3_;
	FsoGsmPlusCNMA* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gint _tmp7_;
	gchar** _tmp8_;
	gchar** _tmp9_;
	gint _tmp9__length1;
	gchar** response;
	gint response_length1;
	gint _response_size_;
	FsoGsmPlusCNMA* _tmp10_;
	gchar** _tmp11_;
	gint _tmp11__length1;
	FsoGsmConstantsAtResponse _tmp12_;
	FsoFrameworkLogger* _tmp13_;
};


static gpointer fso_gsm_at_sms_handler_parent_class = NULL;
extern FsoGsmModem* fso_gsm_theModem;

gpointer wrap_hex_pdu_ref (gpointer instance);
void wrap_hex_pdu_unref (gpointer instance);
GParamSpec* param_spec_wrap_hex_pdu (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_wrap_hex_pdu (GValue* value, gpointer v_object);
void value_take_wrap_hex_pdu (GValue* value, gpointer v_object);
gpointer value_get_wrap_hex_pdu (const GValue* value);
GType wrap_hex_pdu_get_type (void) G_GNUC_CONST;
GType fso_gsm_isms_storage_get_type (void) G_GNUC_CONST;
GType fso_gsm_sms_handler_get_type (void) G_GNUC_CONST;
GType fso_gsm_abstract_sms_handler_get_type (void) G_GNUC_CONST;
GType fso_gsm_at_sms_handler_get_type (void) G_GNUC_CONST;
enum  {
	FSO_GSM_AT_SMS_HANDLER_DUMMY_PROPERTY
};
static void fso_gsm_at_sms_handler_real_retrieveImsiFromSIM_data_free (gpointer _data);
static void fso_gsm_at_sms_handler_real_retrieveImsiFromSIM (FsoGsmAbstractSmsHandler* base, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean fso_gsm_at_sms_handler_real_retrieveImsiFromSIM_co (fso_gsm_at_sms_handler_retrieveImsiFromSIMData* _data_);
GType fso_gsm_channel_get_type (void) G_GNUC_CONST;
GType fso_gsm_modem_status_get_type (void) G_GNUC_CONST;
GType fso_gsm_modem_network_status_get_type (void) G_GNUC_CONST;
gpointer fso_gsm_at_command_sequence_ref (gpointer instance);
void fso_gsm_at_command_sequence_unref (gpointer instance);
GParamSpec* fso_gsm_param_spec_at_command_sequence (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void fso_gsm_value_set_at_command_sequence (GValue* value, gpointer v_object);
void fso_gsm_value_take_at_command_sequence (GValue* value, gpointer v_object);
gpointer fso_gsm_value_get_at_command_sequence (const GValue* value);
GType fso_gsm_at_command_sequence_get_type (void) G_GNUC_CONST;
GType fso_gsm_at_command_queue_command_get_type (void) G_GNUC_CONST;
GQuark fso_gsm_at_command_error_quark (void);
GType fso_gsm_constants_at_response_get_type (void) G_GNUC_CONST;
GType fso_gsm_at_command_get_type (void) G_GNUC_CONST;
GType fso_gsm_modem_data_get_type (void) G_GNUC_CONST;
GType fso_gsm_call_info_get_type (void) G_GNUC_CONST;
GType fso_gsm_call_handler_get_type (void) G_GNUC_CONST;
GType fso_gsm_phonebook_storage_get_type (void) G_GNUC_CONST;
GType fso_gsm_phonebook_handler_get_type (void) G_GNUC_CONST;
GType fso_gsm_watch_dog_get_type (void) G_GNUC_CONST;
gpointer fso_gsm_route_info_ref (gpointer instance);
void fso_gsm_route_info_unref (gpointer instance);
GParamSpec* fso_gsm_param_spec_route_info (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void fso_gsm_value_set_route_info (GValue* value, gpointer v_object);
void fso_gsm_value_take_route_info (GValue* value, gpointer v_object);
gpointer fso_gsm_value_get_route_info (const GValue* value);
GType fso_gsm_route_info_get_type (void) G_GNUC_CONST;
GType fso_gsm_ipdp_handler_get_type (void) G_GNUC_CONST;
GType fso_gsm_modem_get_type (void) G_GNUC_CONST;
gpointer fso_gsm_modem_createAtCommand (FsoGsmModem* self, GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, const gchar* command);
GType fso_gsm_abstract_at_command_get_type (void) G_GNUC_CONST;
GType fso_gsm_simple_at_command_get_type (void) G_GNUC_CONST;
GType fso_gsm_plus_cimi_get_type (void) G_GNUC_CONST;
void fso_gsm_modem_processAtCommandAsync (FsoGsmModem* self, FsoGsmAtCommand* command, const gchar* request, gint retries, GAsyncReadyCallback _callback_, gpointer _user_data_);
gchar** fso_gsm_modem_processAtCommandAsync_finish (FsoGsmModem* self, GAsyncResult* _res_, int* result_length1);
gchar* fso_gsm_simple_at_command_execute (FsoGsmSimpleAtCommand* self);
#define FSO_GSM_MODEM_DEFAULT_RETRIES 3
static void fso_gsm_at_sms_handler_retrieveImsiFromSIM_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
FsoGsmConstantsAtResponse fso_gsm_abstract_at_command_validate (FsoGsmAbstractAtCommand* self, gchar** response, int response_length1);
static void fso_gsm_at_sms_handler_real_fillStorageWithMessageFromSIM_data_free (gpointer _data);
static void fso_gsm_at_sms_handler_real_fillStorageWithMessageFromSIM (FsoGsmAbstractSmsHandler* base, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean fso_gsm_at_sms_handler_real_fillStorageWithMessageFromSIM_co (fso_gsm_at_sms_handler_fillStorageWithMessageFromSIMData* _data_);
GType fso_gsm_plus_cmgl_get_type (void) G_GNUC_CONST;
GType fso_gsm_plus_cmgl_mode_get_type (void) G_GNUC_CONST;
gchar* fso_gsm_plus_cmgl_issue (FsoGsmPlusCMGL* self, FsoGsmPlusCMGLMode mode);
static void fso_gsm_at_sms_handler_fillStorageWithMessageFromSIM_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
FsoGsmConstantsAtResponse fso_gsm_abstract_at_command_validateMulti (FsoGsmAbstractAtCommand* self, gchar** response, int response_length1);
gpointer wrap_sms_ref (gpointer instance);
void wrap_sms_unref (gpointer instance);
GParamSpec* param_spec_wrap_sms (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_wrap_sms (GValue* value, gpointer v_object);
void value_take_wrap_sms (GValue* value, gpointer v_object);
gpointer value_get_wrap_sms (const GValue* value);
GType wrap_sms_get_type (void) G_GNUC_CONST;
FsoGsmISmsStorage* fso_gsm_sms_handler_get_storage (FsoGsmSmsHandler* self);
gint fso_gsm_isms_storage_addSms (FsoGsmISmsStorage* self, struct sms* message);
void fso_gsm_isms_storage_message (FsoGsmISmsStorage* self, const gchar* key, gint index, FreeSmartphoneGSMSIMMessage* result);
gpointer fso_gsm_modem_theDevice (FsoGsmModem* self, GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func);
static void fso_gsm_at_sms_handler_real_readSmsMessageFromSIM_data_free (gpointer _data);
static void fso_gsm_at_sms_handler_real_readSmsMessageFromSIM (FsoGsmAbstractSmsHandler* base, guint index, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean fso_gsm_at_sms_handler_real_readSmsMessageFromSIM_co (fso_gsm_at_sms_handler_readSmsMessageFromSIMData* _data_);
GType fso_gsm_plus_cmgr_get_type (void) G_GNUC_CONST;
gchar* fso_gsm_plus_cmgr_issue (FsoGsmPlusCMGR* self, guint index);
static void fso_gsm_at_sms_handler_readSmsMessageFromSIM_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
FsoGsmConstantsAtResponse fso_gsm_abstract_at_command_validateUrcPdu (FsoGsmAbstractAtCommand* self, gchar** response, int response_length1);
static void fso_gsm_at_sms_handler_real_acknowledgeSmsMessage_data_free (gpointer _data);
static void fso_gsm_at_sms_handler_real_acknowledgeSmsMessage (FsoGsmAbstractSmsHandler* base, gint id, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean fso_gsm_at_sms_handler_real_acknowledgeSmsMessage_co (fso_gsm_at_sms_handler_acknowledgeSmsMessageData* _data_);
GType fso_gsm_plus_cnma_get_type (void) G_GNUC_CONST;
gchar* fso_gsm_simple_at_command_issue (FsoGsmSimpleAtCommand* self, gconstpointer val);
static void fso_gsm_at_sms_handler_acknowledgeSmsMessage_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
FsoGsmAtSmsHandler* fso_gsm_at_sms_handler_new (void);
FsoGsmAtSmsHandler* fso_gsm_at_sms_handler_construct (GType object_type);
FsoGsmAbstractSmsHandler* fso_gsm_abstract_sms_handler_construct (GType object_type);
static gchar* fso_gsm_at_sms_handler_real_repr (FsoFrameworkAbstractObject* base);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static void fso_gsm_at_sms_handler_real_retrieveImsiFromSIM_data_free (gpointer _data) {
	fso_gsm_at_sms_handler_retrieveImsiFromSIMData* _data_;
	_data_ = _data;
	_g_free0 (_data_->result);
	_g_object_unref0 (_data_->self);
	g_slice_free (fso_gsm_at_sms_handler_retrieveImsiFromSIMData, _data_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void fso_gsm_at_sms_handler_real_retrieveImsiFromSIM (FsoGsmAbstractSmsHandler* base, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	FsoGsmAtSmsHandler * self;
	fso_gsm_at_sms_handler_retrieveImsiFromSIMData* _data_;
	FsoGsmAtSmsHandler* _tmp0_;
	self = (FsoGsmAtSmsHandler*) base;
	_data_ = g_slice_new0 (fso_gsm_at_sms_handler_retrieveImsiFromSIMData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, fso_gsm_at_sms_handler_real_retrieveImsiFromSIM);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, fso_gsm_at_sms_handler_real_retrieveImsiFromSIM_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	fso_gsm_at_sms_handler_real_retrieveImsiFromSIM_co (_data_);
}


static gchar* fso_gsm_at_sms_handler_real_retrieveImsiFromSIM_finish (FsoGsmAbstractSmsHandler* base, GAsyncResult* _res_) {
	gchar* result;
	fso_gsm_at_sms_handler_retrieveImsiFromSIMData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
	result = _data_->result;
	_data_->result = NULL;
	return result;
}


static void fso_gsm_at_sms_handler_retrieveImsiFromSIM_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	fso_gsm_at_sms_handler_retrieveImsiFromSIMData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	fso_gsm_at_sms_handler_real_retrieveImsiFromSIM_co (_data_);
}


static gboolean fso_gsm_at_sms_handler_real_retrieveImsiFromSIM_co (fso_gsm_at_sms_handler_retrieveImsiFromSIMData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = fso_gsm_theModem;
	_data_->_tmp1_ = NULL;
	_data_->_tmp1_ = fso_gsm_modem_createAtCommand (_data_->_tmp0_, FSO_GSM_TYPE_PLUS_CIMI, (GBoxedCopyFunc) g_object_ref, g_object_unref, "+CIMI");
	_data_->cimi = (FsoGsmPlusCIMI*) _data_->_tmp1_;
	_data_->_tmp2_ = fso_gsm_theModem;
	_data_->_tmp3_ = _data_->cimi;
	_data_->_tmp4_ = _data_->cimi;
	_data_->_tmp5_ = NULL;
	_data_->_tmp5_ = fso_gsm_simple_at_command_execute ((FsoGsmSimpleAtCommand*) _data_->_tmp4_);
	_data_->_tmp6_ = _data_->_tmp5_;
	_data_->_tmp7_ = 0;
	_data_->_state_ = 1;
	fso_gsm_modem_processAtCommandAsync (_data_->_tmp2_, (FsoGsmAtCommand*) _data_->_tmp3_, _data_->_tmp6_, FSO_GSM_MODEM_DEFAULT_RETRIES, fso_gsm_at_sms_handler_retrieveImsiFromSIM_ready, _data_);
	return FALSE;
	_state_1:
	_data_->_tmp8_ = NULL;
	_data_->_tmp8_ = fso_gsm_modem_processAtCommandAsync_finish (_data_->_tmp2_, _data_->_res_, &_data_->_tmp7_);
	_data_->_tmp9_ = _data_->_tmp8_;
	_data_->_tmp9__length1 = _data_->_tmp7_;
	_g_free0 (_data_->_tmp6_);
	_data_->response = _data_->_tmp9_;
	_data_->response_length1 = _data_->_tmp9__length1;
	_data_->_response_size_ = _data_->response_length1;
	_data_->_tmp10_ = _data_->cimi;
	_data_->_tmp11_ = _data_->response;
	_data_->_tmp11__length1 = _data_->response_length1;
	_data_->_tmp12_ = 0;
	_data_->_tmp12_ = fso_gsm_abstract_at_command_validate ((FsoGsmAbstractAtCommand*) _data_->_tmp10_, _data_->_tmp11_, _data_->_tmp11__length1);
	if (_data_->_tmp12_ != FSO_GSM_CONSTANTS_AT_RESPONSE_VALID) {
		_data_->_tmp13_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
		fso_framework_logger_warning (_data_->_tmp13_, "Can't retrieve IMSI from SIM to be used as identifier for SMS storage");
		_data_->_tmp14_ = g_strdup ("");
		_data_->result = _data_->_tmp14_;
		_data_->response = (_vala_array_free (_data_->response, _data_->response_length1, (GDestroyNotify) g_free), NULL);
		_g_object_unref0 (_data_->cimi);
		if (_data_->_state_ == 0) {
			g_simple_async_result_complete_in_idle (_data_->_async_result);
		} else {
			g_simple_async_result_complete (_data_->_async_result);
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_tmp15_ = _data_->cimi;
	_data_->_tmp16_ = ((FsoGsmSimpleAtCommand*) _data_->_tmp15_)->value;
	_data_->_tmp17_ = g_strdup ((const gchar*) _data_->_tmp16_);
	_data_->result = _data_->_tmp17_;
	_data_->response = (_vala_array_free (_data_->response, _data_->response_length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (_data_->cimi);
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
	_data_->response = (_vala_array_free (_data_->response, _data_->response_length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (_data_->cimi);
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void fso_gsm_at_sms_handler_real_fillStorageWithMessageFromSIM_data_free (gpointer _data) {
	fso_gsm_at_sms_handler_fillStorageWithMessageFromSIMData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (fso_gsm_at_sms_handler_fillStorageWithMessageFromSIMData, _data_);
}


static void fso_gsm_at_sms_handler_real_fillStorageWithMessageFromSIM (FsoGsmAbstractSmsHandler* base, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	FsoGsmAtSmsHandler * self;
	fso_gsm_at_sms_handler_fillStorageWithMessageFromSIMData* _data_;
	FsoGsmAtSmsHandler* _tmp0_;
	self = (FsoGsmAtSmsHandler*) base;
	_data_ = g_slice_new0 (fso_gsm_at_sms_handler_fillStorageWithMessageFromSIMData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, fso_gsm_at_sms_handler_real_fillStorageWithMessageFromSIM);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, fso_gsm_at_sms_handler_real_fillStorageWithMessageFromSIM_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	fso_gsm_at_sms_handler_real_fillStorageWithMessageFromSIM_co (_data_);
}


static void fso_gsm_at_sms_handler_real_fillStorageWithMessageFromSIM_finish (FsoGsmAbstractSmsHandler* base, GAsyncResult* _res_) {
	fso_gsm_at_sms_handler_fillStorageWithMessageFromSIMData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void fso_gsm_at_sms_handler_fillStorageWithMessageFromSIM_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	fso_gsm_at_sms_handler_fillStorageWithMessageFromSIMData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	fso_gsm_at_sms_handler_real_fillStorageWithMessageFromSIM_co (_data_);
}


/**
         * @returns a hashable string for the message that serves as a unique identifier
         * (considering the fragments of a concatenated message as being the same message)
         */
static gchar* sms_number (struct sms* self) {
	gchar* result = NULL;
	enum sms_type _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->type;
	switch (_tmp0_) {
		case SMS_TYPE_DELIVER:
		{
			const gchar* _tmp1_ = NULL;
			gchar* _tmp2_;
			_tmp1_ = sms_address_to_string (&self->deliver.oaddr);
			_tmp2_ = g_strdup (_tmp1_);
			result = _tmp2_;
			return result;
		}
		case SMS_TYPE_SUBMIT:
		{
			const gchar* _tmp3_ = NULL;
			gchar* _tmp4_;
			_tmp3_ = sms_address_to_string (&self->submit.daddr);
			_tmp4_ = g_strdup (_tmp3_);
			result = _tmp4_;
			return result;
		}
		case SMS_TYPE_COMMAND:
		{
			const gchar* _tmp5_ = NULL;
			gchar* _tmp6_;
			_tmp5_ = sms_address_to_string (&self->command.daddr);
			_tmp6_ = g_strdup (_tmp5_);
			result = _tmp6_;
			return result;
		}
		case SMS_TYPE_STATUS_REPORT:
		{
			const gchar* _tmp7_ = NULL;
			gchar* _tmp8_;
			_tmp7_ = sms_address_to_string (&self->status_report.raddr);
			_tmp8_ = g_strdup (_tmp7_);
			result = _tmp8_;
			return result;
		}
		default:
		{
			gchar* _tmp9_;
			_tmp9_ = g_strdup ("unknown");
			result = _tmp9_;
			return result;
		}
	}
}


static gchar* sms_toHexPdu (struct sms* self, gint* tpdulen) {
	gint _vala_tpdulen = 0;
	gchar* result = NULL;
	gint binlen = 0;
	gchar* _tmp0_ = NULL;
	gchar* binpdu;
	gint binpdu_length1;
	gint _binpdu_size_;
	gchar* _tmp1_;
	gint _tmp1__length1;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gboolean _tmp4_ = FALSE;
	gboolean res;
	gboolean _tmp5_;
	gchar* _tmp7_ = NULL;
	gchar* hexpdu;
	gint hexpdu_length1;
	gint _hexpdu_size_;
	gchar* _tmp8_;
	gint _tmp8__length1;
	gint _tmp9_;
	gchar* _tmp10_;
	gint _tmp10__length1;
	gchar* _tmp11_;
	gint _tmp11__length1;
	gchar* _tmp12_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_new0 (gchar, 176);
	binpdu = _tmp0_;
	binpdu_length1 = 176;
	_binpdu_size_ = binpdu_length1;
	_tmp1_ = binpdu;
	_tmp1__length1 = binpdu_length1;
	_tmp4_ = sms_encode (self, &_tmp2_, &_tmp3_, _tmp1_);
	binlen = _tmp2_;
	_vala_tpdulen = _tmp3_;
	res = _tmp4_;
	_tmp5_ = res;
	if (!_tmp5_) {
		gchar* _tmp6_;
		g_warning ("fsogsm3rdparty.vapi:619: %s", "Sms.Message::toHexPdu: could not encode message");
		_vala_tpdulen = -1;
		_tmp6_ = g_strdup ("");
		result = _tmp6_;
		binpdu = (g_free (binpdu), NULL);
		if (tpdulen) {
			*tpdulen = _vala_tpdulen;
		}
		return result;
	}
	_tmp7_ = g_new0 (gchar, 1024);
	hexpdu = _tmp7_;
	hexpdu_length1 = 1024;
	_hexpdu_size_ = hexpdu_length1;
	_tmp8_ = binpdu;
	_tmp8__length1 = binpdu_length1;
	_tmp9_ = binlen;
	_tmp10_ = hexpdu;
	_tmp10__length1 = hexpdu_length1;
	encode_hex_own_buf (_tmp8_, (glong) _tmp9_, (gchar) 0, _tmp10_);
	_tmp11_ = hexpdu;
	_tmp11__length1 = hexpdu_length1;
	_tmp12_ = g_strdup_printf ("%s", (const gchar*) _tmp11_);
	result = _tmp12_;
	hexpdu = (g_free (hexpdu), NULL);
	binpdu = (g_free (binpdu), NULL);
	if (tpdulen) {
		*tpdulen = _vala_tpdulen;
	}
	return result;
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	{
		const gchar* _tmp0_;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_;
		GRegex* _tmp3_;
		GRegex* _tmp4_;
		GRegex* regex;
		GRegex* _tmp5_;
		const gchar* _tmp6_;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		_tmp0_ = old;
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		regex = _tmp4_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch45_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp5_ = regex;
		_tmp6_ = replacement;
		_tmp7_ = g_regex_replace_literal (_tmp5_, self, (gssize) (-1), 0, _tmp6_, 0, &_inner_error_);
		_tmp8_ = _tmp7_;
		if (_inner_error_ != NULL) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch45_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		result = _tmp8_;
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally45;
	__catch45_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally45:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


static gchar* sms_hash (struct sms* self) {
	gchar* result = NULL;
	enum sms_type _tmp0_;
	guint16 ref_num = 0U;
	guint8 max_msgs = 0U;
	guint8 seq_num = 0U;
	gint tpdulen = 0;
	gchar* _tmp1_;
	gchar* hash;
	gchar* _tmp2_ = NULL;
	gchar* oaddr;
	guint16 _tmp3_ = 0U;
	guint8 _tmp4_ = 0U;
	guint8 _tmp5_ = 0U;
	gboolean _tmp6_ = FALSE;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->type;
	g_assert (_tmp0_ == SMS_TYPE_DELIVER);
	_tmp1_ = g_strdup ("");
	hash = _tmp1_;
	_tmp2_ = sms_number (self);
	oaddr = _tmp2_;
	_tmp6_ = sms_extract_concatenation (self, &_tmp3_, &_tmp4_, &_tmp5_);
	ref_num = _tmp3_;
	max_msgs = _tmp4_;
	seq_num = _tmp5_;
	if (!_tmp6_) {
		gint _tmp7_ = 0;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_;
		gchar* _tmp10_ = NULL;
		gchar* _tmp11_;
		gchar* pdu_hash;
		const gchar* _tmp12_;
		const gchar* _tmp13_ = NULL;
		gchar* _tmp14_ = NULL;
		_tmp8_ = sms_toHexPdu (self, &_tmp7_);
		tpdulen = _tmp7_;
		_tmp9_ = _tmp8_;
		_tmp10_ = g_compute_checksum_for_string (G_CHECKSUM_MD5, _tmp9_, (gsize) (-1));
		_tmp11_ = _tmp10_;
		_g_free0 (_tmp9_);
		pdu_hash = _tmp11_;
		_tmp12_ = pdu_hash;
		_tmp13_ = string_to_string (_tmp12_);
		_tmp14_ = g_strconcat (_tmp13_, "_1", NULL);
		_g_free0 (hash);
		hash = _tmp14_;
		_g_free0 (pdu_hash);
	} else {
		const gchar* _tmp15_;
		const gchar* _tmp16_ = NULL;
		guint16 _tmp17_;
		gchar* _tmp18_ = NULL;
		gchar* _tmp19_;
		guint8 _tmp20_;
		gchar* _tmp21_ = NULL;
		gchar* _tmp22_;
		gchar* _tmp23_ = NULL;
		gchar* _tmp24_;
		gchar* _tmp25_ = NULL;
		_tmp15_ = oaddr;
		_tmp16_ = string_to_string (_tmp15_);
		_tmp17_ = ref_num;
		_tmp18_ = g_strdup_printf ("%hu", _tmp17_);
		_tmp19_ = _tmp18_;
		_tmp20_ = max_msgs;
		_tmp21_ = g_strdup_printf ("%hhu", _tmp20_);
		_tmp22_ = _tmp21_;
		_tmp23_ = g_strconcat (_tmp16_, "_", _tmp19_, "_", _tmp22_, NULL);
		_tmp24_ = _tmp23_;
		_tmp25_ = string_replace (_tmp24_, "+", "");
		_g_free0 (hash);
		hash = _tmp25_;
		_g_free0 (_tmp24_);
		_g_free0 (_tmp22_);
		_g_free0 (_tmp19_);
	}
	result = hash;
	_g_free0 (oaddr);
	return result;
}


static gboolean fso_gsm_at_sms_handler_real_fillStorageWithMessageFromSIM_co (fso_gsm_at_sms_handler_fillStorageWithMessageFromSIMData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = fso_gsm_theModem;
	_data_->_tmp1_ = NULL;
	_data_->_tmp1_ = fso_gsm_modem_createAtCommand (_data_->_tmp0_, FSO_GSM_TYPE_PLUS_CMGL, (GBoxedCopyFunc) g_object_ref, g_object_unref, "+CMGL");
	_data_->cmgl = (FsoGsmPlusCMGL*) _data_->_tmp1_;
	_data_->_tmp2_ = fso_gsm_theModem;
	_data_->_tmp3_ = _data_->cmgl;
	_data_->_tmp4_ = _data_->cmgl;
	_data_->_tmp5_ = NULL;
	_data_->_tmp5_ = fso_gsm_plus_cmgl_issue (_data_->_tmp4_, FSO_GSM_PLUS_CMGL_MODE_ALL);
	_data_->_tmp6_ = _data_->_tmp5_;
	_data_->_tmp7_ = 0;
	_data_->_state_ = 1;
	fso_gsm_modem_processAtCommandAsync (_data_->_tmp2_, (FsoGsmAtCommand*) _data_->_tmp3_, _data_->_tmp6_, FSO_GSM_MODEM_DEFAULT_RETRIES, fso_gsm_at_sms_handler_fillStorageWithMessageFromSIM_ready, _data_);
	return FALSE;
	_state_1:
	_data_->_tmp8_ = NULL;
	_data_->_tmp8_ = fso_gsm_modem_processAtCommandAsync_finish (_data_->_tmp2_, _data_->_res_, &_data_->_tmp7_);
	_data_->_tmp9_ = _data_->_tmp8_;
	_data_->_tmp9__length1 = _data_->_tmp7_;
	_g_free0 (_data_->_tmp6_);
	_data_->cmglresponse = _data_->_tmp9_;
	_data_->cmglresponse_length1 = _data_->_tmp9__length1;
	_data_->_cmglresponse_size_ = _data_->cmglresponse_length1;
	_data_->_tmp10_ = _data_->cmgl;
	_data_->_tmp11_ = _data_->cmglresponse;
	_data_->_tmp11__length1 = _data_->cmglresponse_length1;
	_data_->_tmp12_ = 0;
	_data_->_tmp12_ = fso_gsm_abstract_at_command_validateMulti ((FsoGsmAbstractAtCommand*) _data_->_tmp10_, _data_->_tmp11_, _data_->_tmp11__length1);
	if (_data_->_tmp12_ != FSO_GSM_CONSTANTS_AT_RESPONSE_VALID) {
		_data_->_tmp13_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
		fso_framework_logger_warning (_data_->_tmp13_, "Can't synchronize SMS storage with SIM");
		_data_->cmglresponse = (_vala_array_free (_data_->cmglresponse, _data_->cmglresponse_length1, (GDestroyNotify) g_free), NULL);
		_g_object_unref0 (_data_->cmgl);
		if (_data_->_state_ == 0) {
			g_simple_async_result_complete_in_idle (_data_->_async_result);
		} else {
			g_simple_async_result_complete (_data_->_async_result);
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	{
		_data_->_tmp14_ = _data_->cmgl;
		_data_->_tmp15_ = _data_->_tmp14_->messagebook;
		_data_->_tmp16_ = _g_object_ref0 (_data_->_tmp15_);
		_data_->_sms_list = _data_->_tmp16_;
		_data_->_tmp17_ = _data_->_sms_list;
		_data_->_tmp18_ = gee_abstract_collection_get_size ((GeeCollection*) _data_->_tmp17_);
		_data_->_tmp19_ = _data_->_tmp18_;
		_data_->_sms_size = _data_->_tmp19_;
		_data_->_sms_index = -1;
		while (TRUE) {
			_data_->_tmp20_ = _data_->_sms_index;
			_data_->_sms_index = _data_->_tmp20_ + 1;
			_data_->_tmp21_ = _data_->_sms_index;
			_data_->_tmp22_ = _data_->_sms_size;
			if (!(_data_->_tmp21_ < _data_->_tmp22_)) {
				break;
			}
			_data_->_tmp23_ = _data_->_sms_list;
			_data_->_tmp24_ = _data_->_sms_index;
			_data_->_tmp25_ = NULL;
			_data_->_tmp25_ = gee_abstract_list_get ((GeeAbstractList*) _data_->_tmp23_, _data_->_tmp24_);
			_data_->sms = (WrapSms*) _data_->_tmp25_;
			_data_->_tmp26_ = fso_gsm_sms_handler_get_storage ((FsoGsmSmsHandler*) _data_->self);
			_data_->_tmp27_ = _data_->_tmp26_;
			_data_->_tmp28_ = _data_->sms;
			_data_->_tmp29_ = _data_->_tmp28_->message;
			_data_->_tmp30_ = 0;
			_data_->_tmp30_ = fso_gsm_isms_storage_addSms (_data_->_tmp27_, _data_->_tmp29_);
			_data_->ret = _data_->_tmp30_;
			_data_->_tmp31_ = _data_->ret;
			if (_data_->_tmp31_ == 1) {
				_data_->_tmp32_ = fso_gsm_sms_handler_get_storage ((FsoGsmSmsHandler*) _data_->self);
				_data_->_tmp33_ = _data_->_tmp32_;
				_data_->_tmp34_ = _data_->sms;
				_data_->_tmp35_ = _data_->_tmp34_->message;
				_data_->_tmp36_ = NULL;
				_data_->_tmp36_ = sms_hash (_data_->_tmp35_);
				_data_->_tmp37_ = _data_->_tmp36_;
				memset (&_data_->_tmp38_, 0, sizeof (FreeSmartphoneGSMSIMMessage));
				fso_gsm_isms_storage_message (_data_->_tmp33_, _data_->_tmp37_, 0, &_data_->_tmp38_);
				_data_->_tmp39_ = _data_->_tmp38_;
				_g_free0 (_data_->_tmp37_);
				_data_->msg = _data_->_tmp39_;
				_data_->_tmp40_ = fso_gsm_theModem;
				_data_->_tmp41_ = NULL;
				_data_->_tmp41_ = fso_gsm_modem_theDevice (_data_->_tmp40_, FREE_SMARTPHONE_GSM_TYPE_SMS, (GBoxedCopyFunc) g_object_ref, g_object_unref);
				_data_->obj = (FreeSmartphoneGSMSMS*) _data_->_tmp41_;
				_data_->_tmp42_ = _data_->obj;
				_data_->_tmp43_ = _data_->msg;
				_data_->_tmp44_ = _data_->_tmp43_.number;
				_data_->_tmp45_ = _data_->msg;
				_data_->_tmp46_ = _data_->_tmp45_.timestamp;
				_data_->_tmp47_ = _data_->msg;
				_data_->_tmp48_ = _data_->_tmp47_.contents;
				g_signal_emit_by_name (_data_->_tmp42_, "incoming-text-message", _data_->_tmp44_, _data_->_tmp46_, _data_->_tmp48_);
				_g_object_unref0 (_data_->obj);
				free_smartphone_gsm_sim_message_destroy (&_data_->msg);
			}
			_wrap_sms_unref0 (_data_->sms);
		}
		_g_object_unref0 (_data_->_sms_list);
	}
	_data_->cmglresponse = (_vala_array_free (_data_->cmglresponse, _data_->cmglresponse_length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (_data_->cmgl);
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void fso_gsm_at_sms_handler_real_readSmsMessageFromSIM_data_free (gpointer _data) {
	fso_gsm_at_sms_handler_readSmsMessageFromSIMData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (fso_gsm_at_sms_handler_readSmsMessageFromSIMData, _data_);
}


static void fso_gsm_at_sms_handler_real_readSmsMessageFromSIM (FsoGsmAbstractSmsHandler* base, guint index, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	FsoGsmAtSmsHandler * self;
	fso_gsm_at_sms_handler_readSmsMessageFromSIMData* _data_;
	FsoGsmAtSmsHandler* _tmp0_;
	guint _tmp1_;
	self = (FsoGsmAtSmsHandler*) base;
	_data_ = g_slice_new0 (fso_gsm_at_sms_handler_readSmsMessageFromSIMData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, fso_gsm_at_sms_handler_real_readSmsMessageFromSIM);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, fso_gsm_at_sms_handler_real_readSmsMessageFromSIM_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = index;
	_data_->index = _tmp1_;
	fso_gsm_at_sms_handler_real_readSmsMessageFromSIM_co (_data_);
}


static gboolean fso_gsm_at_sms_handler_real_readSmsMessageFromSIM_finish (FsoGsmAbstractSmsHandler* base, GAsyncResult* _res_, gchar** hexpdu, gint* tpdulen) {
	gboolean result;
	fso_gsm_at_sms_handler_readSmsMessageFromSIMData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
	if (hexpdu) {
		*hexpdu = _data_->hexpdu;
	} else {
		_g_free0 (_data_->hexpdu);
	}
	_data_->hexpdu = NULL;
	if (tpdulen) {
		*tpdulen = _data_->tpdulen;
	}
	result = _data_->result;
	return result;
}


static void fso_gsm_at_sms_handler_readSmsMessageFromSIM_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	fso_gsm_at_sms_handler_readSmsMessageFromSIMData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	fso_gsm_at_sms_handler_real_readSmsMessageFromSIM_co (_data_);
}


static gboolean fso_gsm_at_sms_handler_real_readSmsMessageFromSIM_co (fso_gsm_at_sms_handler_readSmsMessageFromSIMData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = g_strdup ("");
	_g_free0 (_data_->hexpdu);
	_data_->hexpdu = _data_->_tmp0_;
	_data_->tpdulen = 0;
	_data_->_tmp1_ = fso_gsm_theModem;
	_data_->_tmp2_ = NULL;
	_data_->_tmp2_ = fso_gsm_modem_createAtCommand (_data_->_tmp1_, FSO_GSM_TYPE_PLUS_CMGR, (GBoxedCopyFunc) g_object_ref, g_object_unref, "+CMGR");
	_data_->cmd = (FsoGsmPlusCMGR*) _data_->_tmp2_;
	_data_->_tmp3_ = fso_gsm_theModem;
	_data_->_tmp4_ = _data_->cmd;
	_data_->_tmp5_ = _data_->cmd;
	_data_->_tmp6_ = _data_->index;
	_data_->_tmp7_ = NULL;
	_data_->_tmp7_ = fso_gsm_plus_cmgr_issue (_data_->_tmp5_, _data_->_tmp6_);
	_data_->_tmp8_ = _data_->_tmp7_;
	_data_->_tmp9_ = 0;
	_data_->_state_ = 1;
	fso_gsm_modem_processAtCommandAsync (_data_->_tmp3_, (FsoGsmAtCommand*) _data_->_tmp4_, _data_->_tmp8_, FSO_GSM_MODEM_DEFAULT_RETRIES, fso_gsm_at_sms_handler_readSmsMessageFromSIM_ready, _data_);
	return FALSE;
	_state_1:
	_data_->_tmp10_ = NULL;
	_data_->_tmp10_ = fso_gsm_modem_processAtCommandAsync_finish (_data_->_tmp3_, _data_->_res_, &_data_->_tmp9_);
	_data_->_tmp11_ = _data_->_tmp10_;
	_data_->_tmp11__length1 = _data_->_tmp9_;
	_g_free0 (_data_->_tmp8_);
	_data_->response = _data_->_tmp11_;
	_data_->response_length1 = _data_->_tmp11__length1;
	_data_->_response_size_ = _data_->response_length1;
	_data_->_tmp12_ = _data_->cmd;
	_data_->_tmp13_ = _data_->response;
	_data_->_tmp13__length1 = _data_->response_length1;
	_data_->_tmp14_ = 0;
	_data_->_tmp14_ = fso_gsm_abstract_at_command_validateUrcPdu ((FsoGsmAbstractAtCommand*) _data_->_tmp12_, _data_->_tmp13_, _data_->_tmp13__length1);
	if (_data_->_tmp14_ != FSO_GSM_CONSTANTS_AT_RESPONSE_VALID) {
		_data_->_tmp15_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
		_data_->_tmp16_ = _data_->index;
		_data_->_tmp17_ = NULL;
		_data_->_tmp17_ = g_strdup_printf ("%u", _data_->_tmp16_);
		_data_->_tmp18_ = _data_->_tmp17_;
		_data_->_tmp19_ = NULL;
		_data_->_tmp19_ = g_strconcat ("Can't read new SMS from SIM storage at index ", _data_->_tmp18_, ".", NULL);
		_data_->_tmp20_ = _data_->_tmp19_;
		fso_framework_logger_warning (_data_->_tmp15_, _data_->_tmp20_);
		_g_free0 (_data_->_tmp20_);
		_g_free0 (_data_->_tmp18_);
		_data_->result = FALSE;
		_data_->response = (_vala_array_free (_data_->response, _data_->response_length1, (GDestroyNotify) g_free), NULL);
		_g_object_unref0 (_data_->cmd);
		if (_data_->_state_ == 0) {
			g_simple_async_result_complete_in_idle (_data_->_async_result);
		} else {
			g_simple_async_result_complete (_data_->_async_result);
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_tmp21_ = _data_->cmd;
	_data_->_tmp22_ = _data_->_tmp21_->hexpdu;
	_data_->_tmp23_ = g_strdup (_data_->_tmp22_);
	_g_free0 (_data_->hexpdu);
	_data_->hexpdu = _data_->_tmp23_;
	_data_->_tmp24_ = _data_->cmd;
	_data_->_tmp25_ = _data_->_tmp24_->tpdulen;
	_data_->tpdulen = _data_->_tmp25_;
	_data_->result = TRUE;
	_data_->response = (_vala_array_free (_data_->response, _data_->response_length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (_data_->cmd);
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
	_data_->response = (_vala_array_free (_data_->response, _data_->response_length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (_data_->cmd);
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void fso_gsm_at_sms_handler_real_acknowledgeSmsMessage_data_free (gpointer _data) {
	fso_gsm_at_sms_handler_acknowledgeSmsMessageData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (fso_gsm_at_sms_handler_acknowledgeSmsMessageData, _data_);
}


static void fso_gsm_at_sms_handler_real_acknowledgeSmsMessage (FsoGsmAbstractSmsHandler* base, gint id, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	FsoGsmAtSmsHandler * self;
	fso_gsm_at_sms_handler_acknowledgeSmsMessageData* _data_;
	FsoGsmAtSmsHandler* _tmp0_;
	gint _tmp1_;
	self = (FsoGsmAtSmsHandler*) base;
	_data_ = g_slice_new0 (fso_gsm_at_sms_handler_acknowledgeSmsMessageData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, fso_gsm_at_sms_handler_real_acknowledgeSmsMessage);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, fso_gsm_at_sms_handler_real_acknowledgeSmsMessage_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = id;
	_data_->id = _tmp1_;
	fso_gsm_at_sms_handler_real_acknowledgeSmsMessage_co (_data_);
}


static gboolean fso_gsm_at_sms_handler_real_acknowledgeSmsMessage_finish (FsoGsmAbstractSmsHandler* base, GAsyncResult* _res_) {
	gboolean result;
	fso_gsm_at_sms_handler_acknowledgeSmsMessageData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
	result = _data_->result;
	return result;
}


static void fso_gsm_at_sms_handler_acknowledgeSmsMessage_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	fso_gsm_at_sms_handler_acknowledgeSmsMessageData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	fso_gsm_at_sms_handler_real_acknowledgeSmsMessage_co (_data_);
}


static gboolean fso_gsm_at_sms_handler_real_acknowledgeSmsMessage_co (fso_gsm_at_sms_handler_acknowledgeSmsMessageData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = fso_gsm_theModem;
	_data_->_tmp1_ = NULL;
	_data_->_tmp1_ = fso_gsm_modem_createAtCommand (_data_->_tmp0_, FSO_GSM_TYPE_PLUS_CNMA, (GBoxedCopyFunc) g_object_ref, g_object_unref, "+CNMA");
	_data_->cmd = (FsoGsmPlusCNMA*) _data_->_tmp1_;
	_data_->_tmp2_ = fso_gsm_theModem;
	_data_->_tmp3_ = _data_->cmd;
	_data_->_tmp4_ = _data_->cmd;
	_data_->_tmp5_ = NULL;
	_data_->_tmp5_ = fso_gsm_simple_at_command_issue ((FsoGsmSimpleAtCommand*) _data_->_tmp4_, GINT_TO_POINTER (0));
	_data_->_tmp6_ = _data_->_tmp5_;
	_data_->_tmp7_ = 0;
	_data_->_state_ = 1;
	fso_gsm_modem_processAtCommandAsync (_data_->_tmp2_, (FsoGsmAtCommand*) _data_->_tmp3_, _data_->_tmp6_, FSO_GSM_MODEM_DEFAULT_RETRIES, fso_gsm_at_sms_handler_acknowledgeSmsMessage_ready, _data_);
	return FALSE;
	_state_1:
	_data_->_tmp8_ = NULL;
	_data_->_tmp8_ = fso_gsm_modem_processAtCommandAsync_finish (_data_->_tmp2_, _data_->_res_, &_data_->_tmp7_);
	_data_->_tmp9_ = _data_->_tmp8_;
	_data_->_tmp9__length1 = _data_->_tmp7_;
	_g_free0 (_data_->_tmp6_);
	_data_->response = _data_->_tmp9_;
	_data_->response_length1 = _data_->_tmp9__length1;
	_data_->_response_size_ = _data_->response_length1;
	_data_->_tmp10_ = _data_->cmd;
	_data_->_tmp11_ = _data_->response;
	_data_->_tmp11__length1 = _data_->response_length1;
	_data_->_tmp12_ = 0;
	_data_->_tmp12_ = fso_gsm_abstract_at_command_validate ((FsoGsmAbstractAtCommand*) _data_->_tmp10_, _data_->_tmp11_, _data_->_tmp11__length1);
	if (_data_->_tmp12_ != FSO_GSM_CONSTANTS_AT_RESPONSE_VALID) {
		_data_->_tmp13_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
		fso_framework_logger_warning (_data_->_tmp13_, "Can't acknowledge new SMS");
		_data_->result = FALSE;
		_data_->response = (_vala_array_free (_data_->response, _data_->response_length1, (GDestroyNotify) g_free), NULL);
		_g_object_unref0 (_data_->cmd);
		if (_data_->_state_ == 0) {
			g_simple_async_result_complete_in_idle (_data_->_async_result);
		} else {
			g_simple_async_result_complete (_data_->_async_result);
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->result = TRUE;
	_data_->response = (_vala_array_free (_data_->response, _data_->response_length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (_data_->cmd);
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
	_data_->response = (_vala_array_free (_data_->response, _data_->response_length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (_data_->cmd);
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


FsoGsmAtSmsHandler* fso_gsm_at_sms_handler_construct (GType object_type) {
	FsoGsmAtSmsHandler * self = NULL;
	self = (FsoGsmAtSmsHandler*) fso_gsm_abstract_sms_handler_construct (object_type);
	return self;
}


FsoGsmAtSmsHandler* fso_gsm_at_sms_handler_new (void) {
	return fso_gsm_at_sms_handler_construct (FSO_GSM_TYPE_AT_SMS_HANDLER);
}


static gchar* fso_gsm_at_sms_handler_real_repr (FsoFrameworkAbstractObject* base) {
	FsoGsmAtSmsHandler * self;
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	FsoGsmISmsStorage* _tmp1_;
	FsoGsmISmsStorage* _tmp2_;
	self = (FsoGsmAtSmsHandler*) base;
	_tmp1_ = fso_gsm_sms_handler_get_storage ((FsoGsmSmsHandler*) self);
	_tmp2_ = _tmp1_;
	if (_tmp2_ != NULL) {
		FsoGsmISmsStorage* _tmp3_;
		FsoGsmISmsStorage* _tmp4_;
		gchar* _tmp5_ = NULL;
		_tmp3_ = fso_gsm_sms_handler_get_storage ((FsoGsmSmsHandler*) self);
		_tmp4_ = _tmp3_;
		_tmp5_ = fso_framework_abstract_object_repr ((FsoFrameworkAbstractObject*) _tmp4_);
		_g_free0 (_tmp0_);
		_tmp0_ = _tmp5_;
	} else {
		gchar* _tmp6_;
		_tmp6_ = g_strdup ("<None>");
		_g_free0 (_tmp0_);
		_tmp0_ = _tmp6_;
	}
	result = _tmp0_;
	return result;
}


static void fso_gsm_at_sms_handler_class_init (FsoGsmAtSmsHandlerClass * klass) {
	fso_gsm_at_sms_handler_parent_class = g_type_class_peek_parent (klass);
	FSO_GSM_ABSTRACT_SMS_HANDLER_CLASS (klass)->retrieveImsiFromSIM = fso_gsm_at_sms_handler_real_retrieveImsiFromSIM;
	FSO_GSM_ABSTRACT_SMS_HANDLER_CLASS (klass)->retrieveImsiFromSIM_finish = fso_gsm_at_sms_handler_real_retrieveImsiFromSIM_finish;
	FSO_GSM_ABSTRACT_SMS_HANDLER_CLASS (klass)->fillStorageWithMessageFromSIM = fso_gsm_at_sms_handler_real_fillStorageWithMessageFromSIM;
	FSO_GSM_ABSTRACT_SMS_HANDLER_CLASS (klass)->fillStorageWithMessageFromSIM_finish = fso_gsm_at_sms_handler_real_fillStorageWithMessageFromSIM_finish;
	FSO_GSM_ABSTRACT_SMS_HANDLER_CLASS (klass)->readSmsMessageFromSIM = fso_gsm_at_sms_handler_real_readSmsMessageFromSIM;
	FSO_GSM_ABSTRACT_SMS_HANDLER_CLASS (klass)->readSmsMessageFromSIM_finish = fso_gsm_at_sms_handler_real_readSmsMessageFromSIM_finish;
	FSO_GSM_ABSTRACT_SMS_HANDLER_CLASS (klass)->acknowledgeSmsMessage = fso_gsm_at_sms_handler_real_acknowledgeSmsMessage;
	FSO_GSM_ABSTRACT_SMS_HANDLER_CLASS (klass)->acknowledgeSmsMessage_finish = fso_gsm_at_sms_handler_real_acknowledgeSmsMessage_finish;
	FSO_FRAMEWORK_ABSTRACT_OBJECT_CLASS (klass)->repr = fso_gsm_at_sms_handler_real_repr;
}


static void fso_gsm_at_sms_handler_instance_init (FsoGsmAtSmsHandler * self) {
}


/**
 * @class AtSmsHandler
 **/
GType fso_gsm_at_sms_handler_get_type (void) {
	static volatile gsize fso_gsm_at_sms_handler_type_id__volatile = 0;
	if (g_once_init_enter (&fso_gsm_at_sms_handler_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FsoGsmAtSmsHandlerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) fso_gsm_at_sms_handler_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FsoGsmAtSmsHandler), 0, (GInstanceInitFunc) fso_gsm_at_sms_handler_instance_init, NULL };
		GType fso_gsm_at_sms_handler_type_id;
		fso_gsm_at_sms_handler_type_id = g_type_register_static (FSO_GSM_TYPE_ABSTRACT_SMS_HANDLER, "FsoGsmAtSmsHandler", &g_define_type_info, 0);
		g_once_init_leave (&fso_gsm_at_sms_handler_type_id__volatile, fso_gsm_at_sms_handler_type_id);
	}
	return fso_gsm_at_sms_handler_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



