/* plugin.c generated by valac 0.16.0, the Vala compiler
 * generated from plugin.vala, do not modify */

/*
 * Copyright (C) 2009-2012 Michael 'Mickey' Lauer <mlauer@vanille-media.de>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <fsobasics.h>
#include <fsogsm.h>
#include <stdlib.h>
#include <string.h>
#include <fsotransport.h>
#include <fsoframework.h>


#define LOW_LEVEL_TYPE_OPENMOKO (low_level_openmoko_get_type ())
#define LOW_LEVEL_OPENMOKO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LOW_LEVEL_TYPE_OPENMOKO, LowLevelOpenmoko))
#define LOW_LEVEL_OPENMOKO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LOW_LEVEL_TYPE_OPENMOKO, LowLevelOpenmokoClass))
#define LOW_LEVEL_IS_OPENMOKO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LOW_LEVEL_TYPE_OPENMOKO))
#define LOW_LEVEL_IS_OPENMOKO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LOW_LEVEL_TYPE_OPENMOKO))
#define LOW_LEVEL_OPENMOKO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LOW_LEVEL_TYPE_OPENMOKO, LowLevelOpenmokoClass))

typedef struct _LowLevelOpenmoko LowLevelOpenmoko;
typedef struct _LowLevelOpenmokoClass LowLevelOpenmokoClass;
typedef struct _LowLevelOpenmokoPrivate LowLevelOpenmokoPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _fso_framework_transport_spec_unref0(var) ((var == NULL) ? NULL : (var = (fso_framework_transport_spec_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _LowLevelOpenmoko {
	FsoFrameworkAbstractObject parent_instance;
	LowLevelOpenmokoPrivate * priv;
};

struct _LowLevelOpenmokoClass {
	FsoFrameworkAbstractObjectClass parent_class;
};

struct _LowLevelOpenmokoPrivate {
	gchar* powerNode;
	gchar* fcNode;
	FsoFrameworkTransportSpec* modem_transport_spec;
};


static gpointer low_level_openmoko_parent_class = NULL;
static FsoGsmLowLevelIface* low_level_openmoko_fso_gsm_low_level_parent_iface = NULL;
static GType low_level_openmoko_type_id = 0;

GType low_level_openmoko_get_type (void) G_GNUC_CONST;
GType low_level_openmoko_register_type (GTypeModule * module);
#define LOW_LEVEL_OPENMOKO_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), LOW_LEVEL_TYPE_OPENMOKO, LowLevelOpenmokoPrivate))
enum  {
	LOW_LEVEL_OPENMOKO_DUMMY_PROPERTY
};
#define LOW_LEVEL_OPENMOKO_MODULE_NAME "fsogsm.lowlevel_openmoko"
#define LOW_LEVEL_OPENMOKO_POWERUP_RETRIES ((guint) 5)
static gchar* low_level_openmoko_real_repr (FsoFrameworkAbstractObject* base);
static gboolean low_level_openmoko_real_poweron (FsoGsmLowLevel* base);
static gboolean low_level_openmoko_real_poweroff (FsoGsmLowLevel* base);
static gboolean low_level_openmoko_real_suspend (FsoGsmLowLevel* base);
static gboolean low_level_openmoko_real_resume (FsoGsmLowLevel* base);
LowLevelOpenmoko* low_level_openmoko_new (void);
LowLevelOpenmoko* low_level_openmoko_construct (GType object_type);
static GObject * low_level_openmoko_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void low_level_openmoko_finalize (GObject* obj);
gchar* fso_factory_function (FsoFrameworkSubsystem* subsystem, GError** error);
void fso_register_function (GTypeModule* module);


static gchar* low_level_openmoko_real_repr (FsoFrameworkAbstractObject* base) {
	LowLevelOpenmoko * self;
	gchar* result = NULL;
	gchar* _tmp0_;
	self = (LowLevelOpenmoko*) base;
	_tmp0_ = g_strdup ("<>");
	result = _tmp0_;
	return result;
}


static gboolean low_level_openmoko_real_poweron (FsoGsmLowLevel* base) {
	LowLevelOpenmoko * self;
	gboolean result = FALSE;
	const gchar* _tmp0_;
	const gchar* _tmp2_;
	FsoFrameworkTransportSpec* _tmp3_;
	FsoFrameworkTransport* _tmp4_ = NULL;
	FsoFrameworkTransport* transport;
	FsoFrameworkTransport* _tmp5_;
	FsoFrameworkTransport* _tmp6_;
	gboolean _tmp7_ = FALSE;
	gchar* _tmp8_ = NULL;
	gchar* buf;
	gint buf_length1;
	gint _buf_size_;
	FsoFrameworkTransport* _tmp9_;
	gchar* _tmp10_;
	gint _tmp10__length1;
	gint _tmp11_ = 0;
	gint bread;
	FsoFrameworkTransport* _tmp12_;
	gchar* _tmp13_;
	gint _tmp13__length1;
	gint _tmp14_ = 0;
	guint i;
	FsoFrameworkTransport* _tmp82_;
	self = (LowLevelOpenmoko*) base;
	_tmp0_ = self->priv->powerNode;
	if (g_strcmp0 (_tmp0_, "unknown") == 0) {
		FsoFrameworkLogger* _tmp1_;
		_tmp1_ = ((FsoFrameworkAbstractObject*) self)->logger;
		fso_framework_logger_error (_tmp1_, "power_node not defined. Can't poweron.");
		result = FALSE;
		return result;
	}
	fso_gsm_low_level_poweroff ((FsoGsmLowLevel*) self);
	g_usleep ((gulong) (1000 * 1000));
	_tmp2_ = self->priv->powerNode;
	fso_framework_file_handling_write ("1\n", _tmp2_, FALSE);
	g_usleep ((gulong) (1000 * 1000));
	_tmp3_ = self->priv->modem_transport_spec;
	_tmp4_ = fso_framework_transport_spec_create (_tmp3_);
	transport = _tmp4_;
	_tmp5_ = transport;
	fso_framework_transport_open (_tmp5_);
	_tmp6_ = transport;
	_tmp7_ = fso_framework_transport_isOpen (_tmp6_);
	g_assert (_tmp7_);
	_tmp8_ = g_new0 (gchar, 512);
	buf = _tmp8_;
	buf_length1 = 512;
	_buf_size_ = buf_length1;
	_tmp9_ = transport;
	_tmp10_ = buf;
	_tmp10__length1 = buf_length1;
	_tmp11_ = fso_framework_transport_writeAndRead (_tmp9_, "AT\r\n", 4, _tmp10_, 512, 0);
	bread = _tmp11_;
	_tmp12_ = transport;
	_tmp13_ = buf;
	_tmp13__length1 = buf_length1;
	_tmp14_ = fso_framework_transport_writeAndRead (_tmp12_, "AT\r\n", 4, _tmp13_, 512, 0);
	bread = _tmp14_;
	i = (guint) 0;
	while (TRUE) {
		guint _tmp15_;
		FsoFrameworkTransport* _tmp16_;
		FsoFrameworkTransport* _tmp17_;
		guint _tmp18_;
		gchar* _tmp19_ = NULL;
		gchar* _tmp20_;
		gchar* _tmp21_ = NULL;
		gchar* _tmp22_;
		FsoFrameworkTransport* _tmp23_;
		gchar* _tmp24_;
		gint _tmp24__length1;
		gint _tmp25_ = 0;
		gchar* _tmp26_;
		gint _tmp26__length1;
		gint _tmp27_;
		gchar _tmp28_;
		gchar* _tmp29_;
		gint _tmp29__length1;
		gchar* _tmp30_ = NULL;
		gchar* displayString;
		gboolean _tmp31_ = FALSE;
		gboolean _tmp32_ = FALSE;
		gboolean _tmp33_ = FALSE;
		gboolean _tmp34_ = FALSE;
		gint _tmp35_;
		gboolean _tmp39_;
		gboolean _tmp43_;
		gboolean _tmp47_;
		gboolean _tmp51_;
		_tmp15_ = i;
		i = _tmp15_ + 1;
		if (!(_tmp15_ < LOW_LEVEL_OPENMOKO_POWERUP_RETRIES)) {
			break;
		}
		_tmp16_ = transport;
		fso_framework_transport_drain (_tmp16_);
		_tmp17_ = transport;
		fso_framework_transport_flush (_tmp17_);
		_tmp18_ = i;
		_tmp19_ = g_strdup_printf ("%u", _tmp18_);
		_tmp20_ = _tmp19_;
		_tmp21_ = g_strconcat (" --- while loop ENTER; i = ", _tmp20_, NULL);
		_tmp22_ = _tmp21_;
		g_debug ("plugin.vala:83: %s", _tmp22_);
		_g_free0 (_tmp22_);
		_g_free0 (_tmp20_);
		_tmp23_ = transport;
		_tmp24_ = buf;
		_tmp24__length1 = buf_length1;
		_tmp25_ = fso_framework_transport_writeAndRead (_tmp23_, "ATE0Q0V1\r\n", 10, _tmp24_, 512, 5000);
		bread = _tmp25_;
		_tmp26_ = buf;
		_tmp26__length1 = buf_length1;
		_tmp27_ = bread;
		_tmp26_[_tmp27_] = '\0';
		_tmp28_ = _tmp26_[_tmp27_];
		_tmp29_ = buf;
		_tmp29__length1 = buf_length1;
		_tmp30_ = g_strescape ((const gchar*) _tmp29_, "");
		displayString = _tmp30_;
		_tmp35_ = bread;
		if (_tmp35_ > 3) {
			gchar* _tmp36_;
			gint _tmp36__length1;
			gint _tmp37_;
			gchar _tmp38_;
			_tmp36_ = buf;
			_tmp36__length1 = buf_length1;
			_tmp37_ = bread;
			_tmp38_ = _tmp36_[_tmp37_ - 1];
			_tmp34_ = _tmp38_ == '\n';
		} else {
			_tmp34_ = FALSE;
		}
		_tmp39_ = _tmp34_;
		if (_tmp39_) {
			gchar* _tmp40_;
			gint _tmp40__length1;
			gint _tmp41_;
			gchar _tmp42_;
			_tmp40_ = buf;
			_tmp40__length1 = buf_length1;
			_tmp41_ = bread;
			_tmp42_ = _tmp40_[_tmp41_ - 2];
			_tmp33_ = _tmp42_ == '\r';
		} else {
			_tmp33_ = FALSE;
		}
		_tmp43_ = _tmp33_;
		if (_tmp43_) {
			gchar* _tmp44_;
			gint _tmp44__length1;
			gint _tmp45_;
			gchar _tmp46_;
			_tmp44_ = buf;
			_tmp44__length1 = buf_length1;
			_tmp45_ = bread;
			_tmp46_ = _tmp44_[_tmp45_ - 3];
			_tmp32_ = _tmp46_ == 'K';
		} else {
			_tmp32_ = FALSE;
		}
		_tmp47_ = _tmp32_;
		if (_tmp47_) {
			gchar* _tmp48_;
			gint _tmp48__length1;
			gint _tmp49_;
			gchar _tmp50_;
			_tmp48_ = buf;
			_tmp48__length1 = buf_length1;
			_tmp49_ = bread;
			_tmp50_ = _tmp48_[_tmp49_ - 4];
			_tmp31_ = _tmp50_ == 'O';
		} else {
			_tmp31_ = FALSE;
		}
		_tmp51_ = _tmp31_;
		if (_tmp51_) {
			FsoFrameworkTransport* _tmp52_;
			gchar* _tmp53_;
			gint _tmp53__length1;
			gint _tmp54_ = 0;
			gchar* _tmp55_;
			gint _tmp55__length1;
			gint _tmp56_;
			gchar _tmp57_;
			gchar* _tmp58_;
			gint _tmp58__length1;
			gchar* _tmp59_ = NULL;
			gboolean _tmp60_ = FALSE;
			gboolean _tmp61_ = FALSE;
			gboolean _tmp62_ = FALSE;
			gboolean _tmp63_ = FALSE;
			gint _tmp64_;
			gboolean _tmp68_;
			gboolean _tmp72_;
			gboolean _tmp76_;
			gboolean _tmp80_;
			_tmp52_ = transport;
			_tmp53_ = buf;
			_tmp53__length1 = buf_length1;
			_tmp54_ = fso_framework_transport_writeAndRead (_tmp52_, "AT%SLEEP=2\r\n", 12, _tmp53_, 512, 5000);
			bread = _tmp54_;
			_tmp55_ = buf;
			_tmp55__length1 = buf_length1;
			_tmp56_ = bread;
			_tmp55_[_tmp56_] = '\0';
			_tmp57_ = _tmp55_[_tmp56_];
			_tmp58_ = buf;
			_tmp58__length1 = buf_length1;
			_tmp59_ = g_strescape ((const gchar*) _tmp58_, "");
			_g_free0 (displayString);
			displayString = _tmp59_;
			_tmp64_ = bread;
			if (_tmp64_ > 3) {
				gchar* _tmp65_;
				gint _tmp65__length1;
				gint _tmp66_;
				gchar _tmp67_;
				_tmp65_ = buf;
				_tmp65__length1 = buf_length1;
				_tmp66_ = bread;
				_tmp67_ = _tmp65_[_tmp66_ - 1];
				_tmp63_ = _tmp67_ == '\n';
			} else {
				_tmp63_ = FALSE;
			}
			_tmp68_ = _tmp63_;
			if (_tmp68_) {
				gchar* _tmp69_;
				gint _tmp69__length1;
				gint _tmp70_;
				gchar _tmp71_;
				_tmp69_ = buf;
				_tmp69__length1 = buf_length1;
				_tmp70_ = bread;
				_tmp71_ = _tmp69_[_tmp70_ - 2];
				_tmp62_ = _tmp71_ == '\r';
			} else {
				_tmp62_ = FALSE;
			}
			_tmp72_ = _tmp62_;
			if (_tmp72_) {
				gchar* _tmp73_;
				gint _tmp73__length1;
				gint _tmp74_;
				gchar _tmp75_;
				_tmp73_ = buf;
				_tmp73__length1 = buf_length1;
				_tmp74_ = bread;
				_tmp75_ = _tmp73_[_tmp74_ - 3];
				_tmp61_ = _tmp75_ == 'K';
			} else {
				_tmp61_ = FALSE;
			}
			_tmp76_ = _tmp61_;
			if (_tmp76_) {
				gchar* _tmp77_;
				gint _tmp77__length1;
				gint _tmp78_;
				gchar _tmp79_;
				_tmp77_ = buf;
				_tmp77__length1 = buf_length1;
				_tmp78_ = bread;
				_tmp79_ = _tmp77_[_tmp78_ - 4];
				_tmp60_ = _tmp79_ == 'O';
			} else {
				_tmp60_ = FALSE;
			}
			_tmp80_ = _tmp60_;
			if (_tmp80_) {
				FsoFrameworkTransport* _tmp81_;
				_tmp81_ = transport;
				fso_framework_transport_close (_tmp81_);
				result = TRUE;
				_g_free0 (displayString);
				buf = (g_free (buf), NULL);
				_g_object_unref0 (transport);
				return result;
			}
		}
		_g_free0 (displayString);
	}
	_tmp82_ = transport;
	fso_framework_transport_close (_tmp82_);
	result = FALSE;
	buf = (g_free (buf), NULL);
	_g_object_unref0 (transport);
	return result;
}


static gboolean low_level_openmoko_real_poweroff (FsoGsmLowLevel* base) {
	LowLevelOpenmoko * self;
	gboolean result = FALSE;
	const gchar* _tmp0_;
	self = (LowLevelOpenmoko*) base;
	_tmp0_ = self->priv->powerNode;
	fso_framework_file_handling_write ("0\n", _tmp0_, FALSE);
	result = TRUE;
	return result;
}


static gboolean low_level_openmoko_real_suspend (FsoGsmLowLevel* base) {
	LowLevelOpenmoko * self;
	gboolean result = FALSE;
	const gchar* _tmp0_;
	const gchar* _tmp2_;
	self = (LowLevelOpenmoko*) base;
	_tmp0_ = self->priv->fcNode;
	if (g_strcmp0 (_tmp0_, "unknown") == 0) {
		FsoFrameworkLogger* _tmp1_;
		_tmp1_ = ((FsoFrameworkAbstractObject*) self)->logger;
		fso_framework_logger_error (_tmp1_, "fc_node not defined. Can't prepare for suspend.");
		result = FALSE;
		return result;
	}
	_tmp2_ = self->priv->fcNode;
	fso_framework_file_handling_write ("1", _tmp2_, FALSE);
	result = TRUE;
	return result;
}


static gboolean low_level_openmoko_real_resume (FsoGsmLowLevel* base) {
	LowLevelOpenmoko * self;
	gboolean result = FALSE;
	const gchar* _tmp0_;
	const gchar* _tmp2_;
	self = (LowLevelOpenmoko*) base;
	_tmp0_ = self->priv->fcNode;
	if (g_strcmp0 (_tmp0_, "unknown") == 0) {
		FsoFrameworkLogger* _tmp1_;
		_tmp1_ = ((FsoFrameworkAbstractObject*) self)->logger;
		fso_framework_logger_error (_tmp1_, "fc_node not defined. Can't recover from suspend.");
		result = FALSE;
		return result;
	}
	_tmp2_ = self->priv->fcNode;
	fso_framework_file_handling_write ("0", _tmp2_, FALSE);
	result = TRUE;
	return result;
}


LowLevelOpenmoko* low_level_openmoko_construct (GType object_type) {
	LowLevelOpenmoko * self = NULL;
	self = (LowLevelOpenmoko*) fso_framework_abstract_object_construct (object_type);
	return self;
}


LowLevelOpenmoko* low_level_openmoko_new (void) {
	return low_level_openmoko_construct (LOW_LEVEL_TYPE_OPENMOKO);
}


static GObject * low_level_openmoko_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	LowLevelOpenmoko * self;
	FsoFrameworkSmartKeyFile* _tmp0_;
	gchar* _tmp1_ = NULL;
	FsoFrameworkSmartKeyFile* _tmp2_;
	gchar* _tmp3_ = NULL;
	FsoFrameworkSmartKeyFile* _tmp4_;
	gchar* _tmp5_ = NULL;
	gchar* modem_config;
	const gchar* _tmp6_;
	FsoFrameworkTransportSpec* _tmp7_ = NULL;
	FsoFrameworkLogger* _tmp8_;
	parent_class = G_OBJECT_CLASS (low_level_openmoko_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = LOW_LEVEL_OPENMOKO (obj);
	_tmp0_ = ((FsoFrameworkAbstractObject*) self)->config;
	_tmp1_ = fso_framework_smart_key_file_stringValue (_tmp0_, LOW_LEVEL_OPENMOKO_MODULE_NAME, "power_node", "unknown");
	_g_free0 (self->priv->powerNode);
	self->priv->powerNode = _tmp1_;
	_tmp2_ = ((FsoFrameworkAbstractObject*) self)->config;
	_tmp3_ = fso_framework_smart_key_file_stringValue (_tmp2_, LOW_LEVEL_OPENMOKO_MODULE_NAME, "fc_node", "unknown");
	_g_free0 (self->priv->fcNode);
	self->priv->fcNode = _tmp3_;
	_tmp4_ = ((FsoFrameworkAbstractObject*) self)->config;
	_tmp5_ = fso_framework_smart_key_file_stringValue (_tmp4_, "fsogsm", "modem_access", "invalid:invalid:-1");
	modem_config = _tmp5_;
	_tmp6_ = modem_config;
	_tmp7_ = fso_framework_transport_spec_parse (_tmp6_);
	_fso_framework_transport_spec_unref0 (self->priv->modem_transport_spec);
	self->priv->modem_transport_spec = _tmp7_;
	_tmp8_ = ((FsoFrameworkAbstractObject*) self)->logger;
	fso_framework_logger_info (_tmp8_, "Registering openmoko low level poweron/poweroff handling");
	_g_free0 (modem_config);
	return obj;
}


static void low_level_openmoko_class_init (LowLevelOpenmokoClass * klass) {
	low_level_openmoko_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LowLevelOpenmokoPrivate));
	FSO_FRAMEWORK_ABSTRACT_OBJECT_CLASS (klass)->repr = low_level_openmoko_real_repr;
	G_OBJECT_CLASS (klass)->constructor = low_level_openmoko_constructor;
	G_OBJECT_CLASS (klass)->finalize = low_level_openmoko_finalize;
}


static void low_level_openmoko_fso_gsm_low_level_interface_init (FsoGsmLowLevelIface * iface) {
	low_level_openmoko_fso_gsm_low_level_parent_iface = g_type_interface_peek_parent (iface);
	iface->poweron = (gboolean (*)(FsoGsmLowLevel*)) low_level_openmoko_real_poweron;
	iface->poweroff = (gboolean (*)(FsoGsmLowLevel*)) low_level_openmoko_real_poweroff;
	iface->suspend = (gboolean (*)(FsoGsmLowLevel*)) low_level_openmoko_real_suspend;
	iface->resume = (gboolean (*)(FsoGsmLowLevel*)) low_level_openmoko_real_resume;
}


static void low_level_openmoko_instance_init (LowLevelOpenmoko * self) {
	self->priv = LOW_LEVEL_OPENMOKO_GET_PRIVATE (self);
}


static void low_level_openmoko_finalize (GObject* obj) {
	LowLevelOpenmoko * self;
	self = LOW_LEVEL_OPENMOKO (obj);
	_g_free0 (self->priv->powerNode);
	_g_free0 (self->priv->fcNode);
	_fso_framework_transport_spec_unref0 (self->priv->modem_transport_spec);
	G_OBJECT_CLASS (low_level_openmoko_parent_class)->finalize (obj);
}


GType low_level_openmoko_get_type (void) {
	return low_level_openmoko_type_id;
}


GType low_level_openmoko_register_type (GTypeModule * module) {
	static const GTypeInfo g_define_type_info = { sizeof (LowLevelOpenmokoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) low_level_openmoko_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LowLevelOpenmoko), 0, (GInstanceInitFunc) low_level_openmoko_instance_init, NULL };
	static const GInterfaceInfo fso_gsm_low_level_info = { (GInterfaceInitFunc) low_level_openmoko_fso_gsm_low_level_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	low_level_openmoko_type_id = g_type_module_register_type (module, FSO_FRAMEWORK_TYPE_ABSTRACT_OBJECT, "LowLevelOpenmoko", &g_define_type_info, 0);
	g_type_module_add_interface (module, low_level_openmoko_type_id, FSO_GSM_TYPE_LOW_LEVEL, &fso_gsm_low_level_info);
	return low_level_openmoko_type_id;
}


/**
 * This function gets called on plugin initialization time.
 * @return the name of your plugin here
 * @note that it needs to be a name in the format <subsystem>.<plugin>
 * else your module will be unloaded immediately.
 **/
gchar* fso_factory_function (FsoFrameworkSubsystem* subsystem, GError** error) {
	gchar* result = NULL;
	FsoFrameworkLogger* _tmp0_;
	gchar* _tmp1_;
	g_return_val_if_fail (subsystem != NULL, NULL);
	_tmp0_ = fso_framework_theLogger;
	fso_framework_logger_debug (_tmp0_, "lowlevel_openmoko fso_factory_function");
	_tmp1_ = g_strdup (LOW_LEVEL_OPENMOKO_MODULE_NAME);
	result = _tmp1_;
	return result;
}


void fso_register_function (GTypeModule* module) {
	g_return_if_fail (module != NULL);
	low_level_openmoko_register_type (module);
}



